/* Fragenkatalog der Lernapp „Ritt zur Friedensstadt“.
   Alle Antworten stammen aus gedrucktem Unterrichtsmaterial (Arbeitsblätter aus dem Sachunterricht, Projektblätter der Stadt Osnabrück).
   Kurzschlüssel: f = Frage, o = Optionen (die erste ist richtig, die App mischt), a = Antwort,
   e = Erklärung nach dem Antworten, t = Tipp {x: Text, q: Quelle, b: Bild}, b = Bild zur Frage, lf = Leitfrage der Lehrkraft. */
window.RITT = {

stationen: [
  { id: "furt", name: "Die Furt an der Hase", zeit: "4000 v. Chr. – 800", bild: "bilder/karte_landschaft.jpg", kurz: "Warum entstand Osnabrück gerade hier?" },
  { id: "gruendung", name: "Karl der Große gründet Osnabrück", zeit: "um 780", bild: "bilder/karl_der_grosse.jpg", kurz: "Sachsen, Franken, Widukind und Bischof Wiho" },
  { id: "stadtteile", name: "Die Stadt wächst", zeit: "780 – 1306", bild: "bilder/karte_stadtteile.jpg", kurz: "Domburg, Binnenburg, Butenburg, Neustadt" },
  { id: "stadtleben", name: "Leben in der alten Stadt", zeit: "Mittelalter", bild: "bilder/fachwerk.jpg", kurz: "Stadtmauer, Fachwerk, Marktplatz und Rathaus", extra: true },
  { id: "reformation", name: "Ablasshandel und Reformation", zeit: "1517", bild: "bilder/luther.jpg", kurz: "Martin Luther und die 95 Thesen" },
  { id: "krieg", name: "Der Dreißigjährige Krieg", zeit: "1555 – 1648", bild: "bilder/fenstersturz.jpg", kurz: "Religionsfrieden, Fenstersturz, Kriegsparteien" },
  { id: "frieden", name: "Der Westfälische Friede", zeit: "1643 – 1648", bild: "bilder/gesandte.jpg", kurz: "Verhandelt in Osnabrück und Münster" },
  { id: "steckenpferd", name: "Das Steckenpferdreiten", zeit: "1650 bis heute", bild: "bilder/brunnen.jpg", kurz: "Woher die Tradition kommt" }
],

fragen: [

/* ───────── Station 1: Die Furt an der Hase ───────── */
{ id: "f1", st: "furt", typ: "mc", lf: true, f: "Wie heißt der Fluss, der durch Osnabrück fließt?",
  o: ["Die Hase", "Die Weser", "Die Ems", "Der Rhein"],
  e: "Die Hase. Früher nannten die Leute sie „Osna“.",
  t: { x: "„Osnabrück liegt im Tal des Flusses Hase – zwischen dem Teutoburger Wald und dem Wiehengebirge.“", q: "Lesetext „Warum entstand Osnabrück gerade an dieser Stelle?“", b: "bilder/karte_landschaft.jpg" } },
{ id: "f2", st: "furt", typ: "wort", f: "Wie hieß die Hase früher? Schreib den alten Namen auf.",
  a: ["Osna"], e: "Die Hase hieß früher „Osna“. Daher kommt der Name Osnabrück.",
  t: { x: "„Früher wurde der Fluss, den wir heute Hase nennen, „Osna“ genannt.“", q: "„Warum entstand Osnabrück gerade an dieser Stelle?“, 1. Grund" } },
{ id: "f3", st: "furt", typ: "mc", f: "Was ist eine Furt?",
  o: ["Eine flache Stelle im Fluss, an der man ihn durchqueren kann", "Eine Brücke aus Stein", "Ein Hügel direkt am Fluss", "Ein Weg durch den Wald"],
  e: "Eine Furt ist eine flache, seichte Stelle im Fluss. Dort konnten Menschen, Tiere und Wagen hinüber.",
  t: { x: "„An dieser Stelle gab es eine flache Stelle im Wasser – eine sogenannte Furt. Dort konnten Menschen und Tiere die Hase leicht überqueren.“", q: "„Warum entstand Osnabrück gerade an dieser Stelle?“", b: "bilder/furt_skizze.jpg" } },
{ id: "f4", st: "furt", typ: "mc", lf: true, f: "Warum entstand Osnabrück gerade hier? Was war der 1. Grund?",
  o: ["An einer Furt konnte man die Hase leicht überqueren", "Hier wurde Gold gefunden", "Hier stand schon ein großes Schloss", "Hier war das Meer ganz nah"],
  e: "1. Grund: die Furt. Die Hügel kamen nah an den Fluss heran, das Tal war schmal, und es gab eine flache Stelle zum Durchqueren. Später baute man dort eine Holzbrücke.",
  t: { x: "„Doch an einer bestimmten Stelle kamen die Hügel des Teutoburger Waldes und des Wiehengebirges ganz nah an den Fluss heran. Das Tal war dort nur etwa 500 Meter breit.“", q: "„Warum entstand Osnabrück gerade an dieser Stelle?“, 1. Grund", b: "bilder/furt_skizze.jpg" } },
{ id: "f5", st: "furt", typ: "mc", lf: true, f: "Und was war der 2. Grund, warum hier eine Siedlung entstand?",
  o: ["Hier kreuzten sich alte Handelswege", "Hier wuchs besonders viel Getreide", "Hier wohnte schon der König", "Hier gab es viele Fische"],
  e: "2. Grund: Wege von Süden nach Norden und von Westen nach Osten trafen sich genau dort, wo man die Hase überqueren konnte.",
  t: { x: "„Hier trafen sich viele alte Wege. […] Genau dort, wo sich die Wege kreuzten und wo man die Hase gut überqueren konnte, entstand eine Siedlung.“", q: "„Warum entstand Osnabrück gerade an dieser Stelle?“, 2. Grund" } },
{ id: "f6", st: "furt", typ: "mc", f: "Zwischen welchen zwei Gebirgen liegt Osnabrück?",
  o: ["Teutoburger Wald und Wiehengebirge", "Harz und Eifel", "Alpen und Teutoburger Wald", "Wiehengebirge und Schwarzwald"],
  e: "Osnabrück liegt im Tal der Hase zwischen dem Teutoburger Wald (früher Osning) und dem Wiehengebirge (früher Süntel).",
  t: { x: "„… zwischen dem Teutoburger Wald (früher Osning genannt) und dem Wiehengebirge (früher Süntel).“", q: "„Warum entstand Osnabrück gerade an dieser Stelle?“" } },
{ id: "f7", st: "furt", typ: "paare", f: "Welcher Berg liegt auf welcher Seite der Hase? Verbinde.",
  p: [["östlich der Hase", "Gertrudenberg"], ["westlich der Hase", "Westerberg"]],
  e: "Östlich liegt der Gertrudenberg, westlich der Westerberg. Merkhilfe: West-erberg liegt im Westen.",
  t: { x: "„Östlich des Flusses liegt der Gertrudenberg, westlich der Westerberg.“ Auf der Karte steht der Westerberg links, der Gertrudenberg oben rechts.", q: "Lückentext „Warum entstand Osnabrück …“ und Karte „Landschaft an der Hase“", b: "bilder/karte_landschaft.jpg" } },
{ id: "f8", st: "furt", typ: "luecke", f: "Setze die alten Namen ein.",
  s: "Die Siedlung an der Furt hieß zuerst ___ und später ___. Daraus wurde im Laufe der Zeit Osnabrück.",
  a: ["Osnabruga", "Osenbrügge"], o: ["Osnabruga", "Osenbrügge", "Westerberg", "Wiehengebirge"],
  e: "Erst Osnabruga, dann Osenbrügge, daraus wurde Osnabrück.",
  t: { x: "„Sie hieß zuerst Osnabruga oder Osnabrügge. Aus diesem Namen wurde später Osnabrück.“ Im Lückentext steht: „… wurde „Osnabruga“ und später „Osenbrügge“ genannt.“", q: "Lesetext und Lückentext „Warum entstand Osnabrück gerade an dieser Stelle?“" } },
{ id: "f9", st: "furt", typ: "mc", f: "Was steckt im Namen „Osnabrück“?",
  o: ["Die Brücke über die Osna", "Die Burg an der Osna", "Die Stadt der Hasen", "Der Wald an der Hase"],
  e: "Osna + Brücke: An der Furt wurde später eine Brücke über die Osna gebaut. So wurde aus der Brücke über die Osna die Stadt Osnabrück.",
  t: { x: "„Deswegen baute man an dieser Stelle eine Brücke. So wurde aus der Brücke über die Osna die Stadt Osnabrück.“", q: "Blatt „Die Entstehung Osnabrücks“" } },
{ id: "f10", st: "furt", typ: "mc", f: "Wo ungefähr lag die Furt durch die Hase?",
  o: ["Dort, wo heute der Dom steht", "Am heutigen Hauptbahnhof", "Am Schloss", "Oben auf dem Westerberg"],
  e: "Die Furt lag etwa dort, wo heute der Dom steht. Dort begann die Geschichte der Stadt.",
  t: { x: "„Eine solche Stelle war etwa dort, wo heute der ___ steht.“ Und im Text „Die Domburg“: Karl der Große ließ „an einem Haseübergang (Furt) eine Bischofskirche bauen“.", q: "Lückentext „Warum entstand Osnabrück …“ und „Wie Osnabrück entstand – 1. Die Domburg“" } },
{ id: "f11", st: "furt", typ: "mc", f: "Wann lebten schon Jäger im Osnabrücker Land?",
  o: ["Etwa 4000 bis 2000 Jahre vor Christus", "Um das Jahr 780", "Um das Jahr 1300", "Im Jahr 1648"],
  e: "Schon in der Steinzeit, etwa 4000 bis 2000 vor Christus, lebten hier Jäger. Später kamen Bauern.",
  t: { x: "„Schon in der Steinzeit lebten hier Jäger. Das war vor etwa 4000 bis 2000 Jahren vor Christus.“", q: "„Warum entstand Osnabrück gerade an dieser Stelle?“", b: "bilder/leitfragen_1.jpg" } },
{ id: "f12", st: "furt", typ: "mc", f: "Wann kamen die Germanen aus dem Norden ins Osnabrücker Land?",
  o: ["Etwa 1000 Jahre vor Christus", "Im Jahr 1517", "Um das Jahr 1300", "Im Jahr 1948"],
  e: "Etwa 1000 Jahre vor Christus. (Auf dem Übersichtsblatt aus dem Unterricht steht „vor 1000 Jahren“ – im Lesetext steht „vor Christus“.)",
  t: { x: "„Etwa 1000 Jahre vor Christus kamen Germanen aus dem Norden und ließen sich hier nieder.“", q: "„Warum entstand Osnabrück gerade an dieser Stelle?“" } },
{ id: "f13", st: "furt", typ: "mc", f: "Warum war es früher schwer, über die Hase zu kommen?",
  o: ["Der Fluss war tief und breit, die Ufer waren sumpfig", "Der Fluss war immer zugefroren", "Man musste Zoll bezahlen", "Es gab dort wilde Tiere"],
  e: "Die Osna war tief und breit, an den Ufern lagen sumpfige Wälder. Wagen und Karren blieben oft im Sumpf stecken.",
  t: { x: "„An den Ufern lagen sumpfige Wälder, durch die man nur schwer gehen konnte. […] Wagen und Karren blieben oft im Sumpf stecken.“", q: "„Warum entstand Osnabrück gerade an dieser Stelle?“" } },
{ id: "f14", st: "furt", typ: "mc", f: "Woran erkennt man oft Städte, die an einer Furt entstanden sind?",
  o: ["Am Namen, zum Beispiel Frankfurt", "An der Farbe der Dächer", "An einem großen Bahnhof", "Daran, dass sie am Meer liegen"],
  e: "Am Namen: Städte auf -furt wie Frankfurt sind an einer Furt entstanden.",
  t: { x: "„Auch andere Städte haben an einer Furt ihren Anfang genommen. Man kann sie an ihrem Namen erkennen.“", q: "Lückentext „Warum entstand Osnabrück gerade an dieser Stelle?“" } },
{ id: "f15", st: "furt", typ: "mc", f: "Warum siedelten sich Menschen an einem Ort an? Welcher Grund steht NICHT auf dem Blatt „Wie entsteht ein Ort?“",
  o: ["Weil es dort einen Spielplatz gab", "Weil sich dort Handelswege kreuzten", "Weil eine Burg Schutz bot", "Weil es dort Wasser gab"],
  e: "Gründe waren: eine Furt, Wasser, Rohstoffe, der Schutz einer Burg, Kreuzungen von Handelswegen und heute große Werke.",
  t: { x: "Texte A bis F: Furt (A), Gewässer (B), Rohstoffe (C), Burg (D), großes Werk (E), Kreuzung von Handelswegen (F).", q: "Blatt „Wie entsteht ein Ort?“", b: "bilder/orte_bilder.jpg" } },

/* ───────── Station 2: Karl der Große gründet Osnabrück ───────── */
{ id: "g1", st: "gruendung", typ: "mc", lf: true, f: "Wer lebte im Osnabrücker Land, bevor Karl der Große kam?",
  o: ["Die Sachsen", "Die Römer", "Die Franken", "Die Schweden"],
  e: "Die Sachsen. Sie waren Germanen und glaubten an viele Götter.",
  t: { x: "„Vor etwa 2000 Jahren lebten im Osnabrücker Land die Germanen. Sie wurden auch Sachsen genannt.“", q: "Lesetext „Von der Gründung der Stadt Osnabrück“" } },
{ id: "g2", st: "gruendung", typ: "mc", f: "Woran glaubten die Sachsen?",
  o: ["An viele Götter", "An einen Gott, wie die Christen", "An den Kaiser", "An gar nichts"],
  e: "Die Sachsen glaubten an viele Götter und brachten ihnen Opfer, zum Beispiel Tiere oder Früchte. Man nannte sie Heiden.",
  t: { x: "„Die Sachsen glaubten an viele Götter. Sie brachten ihnen Opfer dar – zum Beispiel Tiere oder Früchte, die sie auf Steinaltären niederlegten.“", q: "„Von der Gründung der Stadt Osnabrück“" } },
{ id: "g3", st: "gruendung", typ: "mc", lf: true, f: "„Wer bin ich?“ Schau dir das Bild an.", b: "bilder/karl_der_grosse.jpg",
  o: ["Karl der Große", "Martin Luther", "Bischof Wiho", "Herzog Widukind"],
  e: "Das ist Karl der Große, der mächtige König der Franken. Er gilt als Gründer von Osnabrück.",
  t: { x: "Auf dem Bild siehst du einen König mit Krone. Er kam um das Jahr 800 mit seinem Heer ins Land der Sachsen.", q: "Bild im Lesetext „Von der Gründung der Stadt Osnabrück“ und auf dem Übersichtsblatt" } },
{ id: "g4", st: "gruendung", typ: "mc", lf: true, f: "Wie hießen die beiden Völker, die gegeneinander kämpften?",
  o: ["Sachsen und Franken", "Sachsen und Schweden", "Franken und Römer", "Katholiken und Protestanten"],
  e: "Die Sachsen (die Menschen im Osnabrücker Land) kämpften gegen die Franken unter Karl dem Großen.",
  t: { x: "„Karl der Große war ein mächtiger König der Franken. […] Deshalb kämpften sie [die Sachsen] gegen Karl den Großen.“", q: "„Von der Gründung der Stadt Osnabrück“" } },
{ id: "g5", st: "gruendung", typ: "paare", lf: true, f: "Wer war der Anführer welcher Gruppe? Verbinde.",
  p: [["Sachsen", "Herzog Widukind"], ["Franken", "Karl der Große"]],
  e: "Herzog Widukind führte die Sachsen, Karl der Große war König der Franken.",
  t: { x: "„Ihr Anführer, Herzog Widukind, ließ sich als einer der Letzten taufen.“ – „Karl der Große war ein mächtiger König der Franken.“", q: "„Von der Gründung der Stadt Osnabrück“" } },
{ id: "g6", st: "gruendung", typ: "mc", f: "Wo lebten die Franken damals?",
  o: ["In dem Gebiet, das heute Frankreich heißt", "In Schweden", "Im Osnabrücker Land", "In Spanien"],
  e: "Die Franken lebten in dem Gebiet, das heute Frankreich heißt.",
  t: { x: "„Die Franken lebten damals in dem Gebiet, das heute Frankreich heißt.“", q: "„Von der Gründung der Stadt Osnabrück“" } },
{ id: "g7", st: "gruendung", typ: "mc", f: "Warum kämpfte Karl der Große gegen die Sachsen?",
  o: ["Er wollte, dass die Sachsen Christen werden", "Er wollte ihr Gold haben", "Die Sachsen hatten seine Burg zerstört", "Er wollte die Hase besitzen"],
  e: "Karl war Christ und wollte, dass auch die Sachsen Christen werden, sogar mit Gewalt. Die Sachsen wollten ihre alten Götter behalten und frei bleiben.",
  t: { x: "„Karl wollte, dass auch die Sachsen Christen wurden – und zwar mit Gewalt. Doch die Sachsen liebten ihre alten Götter und wollten frei bleiben.“", q: "„Von der Gründung der Stadt Osnabrück“" } },
{ id: "g8", st: "gruendung", typ: "mc", f: "Wie ging der Kampf zwischen Sachsen und Franken aus?",
  o: ["Die Sachsen gaben auf, Widukind ließ sich taufen", "Die Sachsen gewannen", "Karl der Große ließ sich taufen", "Es gab keinen Sieger"],
  e: "Karls Heer war zu stark. Die Sachsen gaben auf, und Herzog Widukind ließ sich als einer der Letzten taufen.",
  t: { x: "„Anfangs wehrten sie sich tapfer, doch Karls Heer war zu stark. Schließlich gaben die Sachsen auf.“", q: "„Von der Gründung der Stadt Osnabrück“" } },
{ id: "g9", st: "gruendung", typ: "jahr", lf: true, f: "Um welches Jahr ließ Karl der Große an der Furt eine Bischofskirche bauen?",
  a: 780, e: "Um das Jahr 780. Daraus entstand die Domburg.",
  t: { x: "„Karl der Große ließ um das Jahr 7_0 herum an einem Haseübergang (Furt) eine Bischofskirche bauen.“ (Eine Ziffer ist versteckt.)", q: "Lesetext „Wie Osnabrück entstand – 1. Die Domburg“" } },
{ id: "g10", st: "gruendung", typ: "mc", lf: true, f: "Wer wurde von Karl dem Großen neu eingesetzt?",
  o: ["Wiho als erster Bischof von Osnabrück", "Widukind als König", "Luther als Pfarrer", "Ein Bürgermeister"],
  e: "Karl setzte Wiho als ersten Bischof von Osnabrück ein.",
  t: { x: "„Den ersten Bischof nannte er Wiho. Dieser sollte den Sachsen den christlichen Glauben beibringen.“", q: "„Von der Gründung der Stadt Osnabrück“" } },
{ id: "g11", st: "gruendung", typ: "wort", f: "Wie hieß der erste Bischof von Osnabrück?",
  a: ["Wiho", "Bischof Wiho"], e: "Er hieß Wiho. Nicht verwechseln mit Widukind, dem Herzog der Sachsen!",
  t: { x: "Der Name hat nur vier Buchstaben und beginnt mit W. „Karl bestimmte den Priester W___ für die Mission im Osnabrücker Land.“", q: "Lesetext „Bischof Wiho baut einen Dom“" } },
{ id: "g12", st: "gruendung", typ: "mc", f: "Stimmt das? „Widukind war der erste Bischof von Osnabrück.“",
  o: ["Falsch", "Richtig"],
  e: "Falsch! Widukind war der Herzog (Anführer) der Sachsen. Der erste Bischof hieß Wiho. Merkhilfe: Widu-KIND ließ sich am Ende taufen wie ein Kind, Wiho wurde Bischof im Dom.",
  t: { x: "Herzog Widukind kämpfte gegen Karl den Großen. Wiho kam als Priester aus Lüttich und baute den Dom.", q: "„Von der Gründung der Stadt Osnabrück“ und „Bischof Wiho baut einen Dom“" } },
{ id: "g13", st: "gruendung", typ: "mc", f: "Welche Aufgabe hatte Bischof Wiho?",
  o: ["Er sollte den Sachsen den christlichen Glauben beibringen", "Er sollte Burgen erobern", "Er sollte Handel treiben", "Er sollte eine Brücke bauen"],
  e: "Wiho sollte die heidnischen Sachsen zum Christentum bekehren, also ihnen den christlichen Glauben beibringen.",
  t: { x: "„Von hier aus sollten die heidnischen Sachsen zum Christentum bekehrt werden.“", q: "„Wie Osnabrück entstand – 1. Die Domburg“" } },
{ id: "g14", st: "gruendung", typ: "mc", f: "Was entstand neben dem Dom außerdem?",
  o: ["Eine Schule, heute das Gymnasium Carolinum", "Ein Bahnhof", "Ein Rathaus", "Ein Fußballstadion"],
  e: "Neben der Kirche entstand eine Schule. An dieser Stelle steht heute das Gymnasium Carolinum.",
  t: { x: "„Neben der Kirche entstand eine Schule, in der junge Menschen etwas über den Glauben lernen sollten. An dieser Stelle steht heute das Gymnasium Carolinum.“", q: "„Von der Gründung der Stadt Osnabrück“" } },
{ id: "g15", st: "gruendung", typ: "mc", f: "Aus welcher Stadt kam Wiho?",
  o: ["Aus Lüttich", "Aus Münster", "Aus Prag", "Aus Nürnberg"],
  e: "Wiho ritt mit anderen Missionaren aus seiner Heimatstadt Lüttich nach Osnabrück.",
  t: { x: "„Nach einigen Wochen ritt Wiho mit einigen anderen Missionaren aus seiner Heimatstadt Lüttich los.“", q: "„Bischof Wiho baut einen Dom“" } },
{ id: "g16", st: "gruendung", typ: "mc", f: "Wer gilt heute als Gründer der Stadt Osnabrück?",
  o: ["Karl der Große", "Bischof Wiho", "Herzog Widukind", "Martin Luther"],
  e: "Karl der Große gilt als Gründer der Stadt Osnabrück.",
  t: { x: "„Darum gilt Karl der Große heute als Gründer der Stadt Osnabrück.“", q: "„Von der Gründung der Stadt Osnabrück“" } },
{ id: "g17", st: "gruendung", typ: "mc", f: "Warum wählte Karl gerade Osnabrück für eine Domburg?",
  o: ["Von dort gingen viele Wege ins Land", "Dort gab es Gold", "Dort wohnte Widukind", "Dort war es besonders warm"],
  e: "An der Hasebrücke trafen sich wichtige Handelswege. Karl dachte: Von dort gehen viele Wege ins Land, ein guter Ort für einen Bischof.",
  t: { x: "Karl dachte: „Von dort gehen viele Wege ins Land. Das ist ein guter Ort für eine Domburg, von der aus ein Bischof die heidnischen Sachsen zum Christentum bekehren kann.“", q: "„Bischof Wiho baut einen Dom“", b: "bilder/karte_um800.jpg" } },

/* ───────── Station 3: Die Stadt wächst ───────── */
{ id: "s1", st: "stadtteile", typ: "reihe", f: "Bring die Stadtteile in die Reihenfolge, in der sie entstanden sind.",
  o: ["Domburg", "Binnenburg", "Butenburg", "Neustadt"],
  e: "Domburg (um 780) → Binnenburg (um 1000) → Butenburg (um 1200) → Neustadt (um 1300).",
  t: { x: "Die Blätter „Wie Osnabrück entstand“ heißen: 1. Die Domburg, 2. Die Erweiterung zur Binnenburg, 3. Die Entstehung der Butenburg, 4. Neben der Altstadt entsteht die Neustadt.", q: "„Wie Osnabrück entstand“, Teil 1 bis 4" } },
{ id: "s2", st: "stadtteile", typ: "paare", lf: true, f: "Welche Kirche gehört zu welchem Stadtteil? Verbinde.",
  p: [["Domburg", "Dom"], ["Binnenburg", "Marienkirche"], ["Butenburg", "Katharinenkirche"], ["Neustadt", "Johanniskirche"]],
  e: "Domburg – Dom, Binnenburg – Marienkirche, Butenburg – Katharinenkirche, Neustadt – Johanniskirche.",
  t: { x: "„… bauten sich ihre eigene Kirche: die Marienkirche.“ (Binnenburg) – „Auch in der Butenburg wurde eine Kirche gebaut: die Katharinenkirche.“ – „… eine neue Kirche (die heutige Johanniskirche)“ (Neustadt).", q: "„Wie Osnabrück entstand“, Teil 2 bis 4" } },
{ id: "s3", st: "stadtteile", typ: "paare", f: "Wann entstand welcher Stadtteil? Verbinde.",
  p: [["Domburg", "um 780"], ["Binnenburg", "um 1000"], ["Butenburg", "um 1200"], ["Neustadt", "um 1300"]],
  e: "Alle 200 Jahre ungefähr ein neuer Teil: 780, 1000, 1200, 1300.",
  t: { x: "Die Überschriften: „Die Erweiterung zur Binnenburg (um das Jahr 1000)“, „Die Entstehung der Butenburg um das Jahr 1200 herum“, „… entsteht die Neustadt um das Jahr 1300 herum“.", q: "„Wie Osnabrück entstand“, Teil 2 bis 4", b: "bilder/leitfragen_1.jpg" } },
{ id: "s4", st: "stadtteile", typ: "jahr", f: "Um welches Jahr entstand die Binnenburg?", a: 1000,
  e: "Um das Jahr 1000.", t: { x: "Schau auf den Zeitstrahl aus dem Unterricht: Die Binnenburg steht beim ersten Jahr im zweiten Pfeil.", q: "Übersichtsblatt aus dem Unterricht und „Wie Osnabrück entstand – 2. Binnenburg“", b: "bilder/leitfragen_1.jpg" } },
{ id: "s5", st: "stadtteile", typ: "jahr", f: "Um welches Jahr entstand die Butenburg?", a: 1200,
  e: "Um das Jahr 1200.", t: { x: "„Die Entstehung der Butenburg um das Jahr 1_00 herum“ (eine Ziffer ist versteckt)", q: "„Wie Osnabrück entstand – 3. Die Butenburg“" } },
{ id: "s6", st: "stadtteile", typ: "jahr", f: "Um welches Jahr entstand die Neustadt?", a: 1300,
  e: "Um das Jahr 1300.", t: { x: "„Neben der Altstadt entsteht die Neustadt um das Jahr 1_00 herum“ (eine Ziffer ist versteckt)", q: "„Wie Osnabrück entstand – 4. Die Neustadt“" } },
{ id: "s7", st: "stadtteile", typ: "jahr", f: "In welchem Jahr vereinigten sich Altstadt und Neustadt und bauten eine gemeinsame Stadtmauer?", a: 1306,
  e: "Im Jahr 1306.", t: { x: "„Im Jahre 13_6 vereinigten sich die beiden Teile der Stadt und es wurde eine neue gemeinsame Stadtmauer erbaut.“", q: "„Wie Osnabrück entstand – 4. Die Neustadt“" } },
{ id: "s8", st: "stadtteile", typ: "mc", lf: true, f: "Wer lebte in der Domburg?",
  o: ["Der Bischof, Priester, Schüler, Knechte, Mägde und Handwerker", "Karl der Große mit seinem Heer", "Nur Händler mit ihren Familien", "Die Sachsen-Krieger"],
  e: "In der Domburg lebten nur wenige Menschen: der Bischof und seine Priester, die Schüler der Domschule und einige Knechte, Mägde und Handwerker. Karl der Große lebte nicht dort!",
  t: { x: "„Nur wenige Menschen lebten in der Domburg: der Bischof und seine Priester, die Schüler der Domschule und einige Knechte, Mägde und Handwerker.“", q: "„Wie Osnabrück entstand – 2. Binnenburg“" } },
{ id: "s9", st: "stadtteile", typ: "mc", lf: true, f: "Was entstand in der Domburg?",
  o: ["Dom, Kloster, Schule, Priesterhäuser, Kornspeicher und Ställe", "Der Marktplatz und das Rathaus", "Das Schloss", "Die Johanniskirche"],
  e: "Um den Dom herum entstanden ein Kloster, eine Schule (das heutige Carolinum), Häuser für die Priester, Kornspeicher, Ställe und Handwerkshäuser.",
  t: { x: "„Um den Dom herum wurde noch ein Kloster und eine Schule (das heutige Carolinum) gebaut, sowie einige Häuser für die Priester. Es kamen noch Kornspeicher, Ställe und einige Handwerkshäuser hinzu.“", q: "„Wie Osnabrück entstand – 1. Die Domburg“", b: "bilder/karte_um800.jpg" } },
{ id: "s10", st: "stadtteile", typ: "mc", lf: true, f: "Wie wurde die Domburg vor Feinden geschützt?",
  o: ["Mit einem starken Zaun", "Mit einer hohen Steinmauer und Türmen", "Mit Kanonen", "Gar nicht"],
  e: "Die Domburg wurde mit einem starken Zaun umgeben. (Im Text über die Stadtmauer steht: Erdwälle und ein Palisadenzaun.)",
  t: { x: "„Zum Schutz gegen Feinde wurde sie mit einem starken Zaun umgeben.“", q: "„Wie Osnabrück entstand – 1. Die Domburg“" } },
{ id: "s11", st: "stadtteile", typ: "mc", f: "Wer baute die Marienkirche?",
  o: ["Die Händler und Handwerker, die am Markt wohnten", "Der Bischof", "Karl der Große", "Die Schweden"],
  e: "Die Händler und Handwerker rund um den Marktplatz bauten sich ihre eigene Kirche: die Marienkirche.",
  t: { x: "„… und die Händler und Handwerker, die dort wohnten, bauten sich ihre eigene Kirche: die Marienkirche.“", q: "„Wie Osnabrück entstand – 2. Binnenburg“" } },
{ id: "s12", st: "stadtteile", typ: "mc", lf: true, f: "Was entstand in der Binnenburg?",
  o: ["Viele Häuser und kleine Gassen rund um den Marktplatz", "Das Kloster und die Domschule", "Die Johanniskirche und neue Schulen", "Große Fabriken"],
  e: "Rund um den Marktplatz entstanden viele Häuser und kleine Gassen. Dort wohnten Händler und Handwerker.",
  t: { x: "„Rund um den Marktplatz entstanden viele Häuser und kleine Gassen …“", q: "„Wie Osnabrück entstand – 2. Binnenburg“", b: "bilder/karte_um1100.jpg" } },
{ id: "s13", st: "stadtteile", typ: "mc", lf: true, f: "Wie schützten sich die Bewohner der Binnenburg?",
  o: ["Mit einem großen Wall und einem breiten Graben", "Mit einem Holzzaun", "Mit einer Steinmauer und Kanonen", "Mit Soldaten aus Schweden"],
  e: "Sie schütteten einen großen Wall auf und legten einen breiten Graben davor an, zusammen mit der Domburg.",
  t: { x: "„Sie schütteten einen großen Wall auf und legten einen breiten Graben davor an.“", q: "„Wie Osnabrück entstand – 2. Binnenburg“" } },
{ id: "s14", st: "stadtteile", typ: "mc", f: "Wie nannten sich die Menschen, die in der Binnenburg lebten?",
  o: ["Bürger", "Sachsen", "Franken", "Mönche"],
  e: "Sie nannten sich Bürger.",
  t: { x: "„Alles zusammen wurde die Binnenburg genannt und die Menschen, die dort lebten, nannten sich ___.“ Das Wort steckt in „Binnen-burg“.", q: "„Wie Osnabrück entstand – 2. Binnenburg“" } },
{ id: "s15", st: "stadtteile", typ: "paare", f: "Was bedeuten die alten Wörter? Verbinde.",
  p: [["binnen", "drinnen"], ["buten", "draußen"]],
  e: "Binnenburg = die Burg drinnen, Butenburg = die Siedlung draußen davor.",
  t: { x: "„Binnenburg (binnen = drinnen) und Butenburg (buten = draußen) …“", q: "„Wie Osnabrück entstand – 3. Die Butenburg“" } },
{ id: "s16", st: "stadtteile", typ: "mc", lf: true, f: "Wer siedelte sich in der Butenburg an?",
  o: ["Immer mehr Handwerker und jetzt auch Bauern", "Nur Mönche", "Soldaten des Kaisers", "Gesandte aus ganz Europa"],
  e: "Immer mehr Handwerker und jetzt auch Bauern siedelten sich um die Binnenburg herum an.",
  t: { x: "„Immer mehr Handwerker und jetzt auch Bauern siedelten sich um die Binnenburg herum an.“", q: "„Wie Osnabrück entstand – 3. Die Butenburg“" } },
{ id: "s17", st: "stadtteile", typ: "mc", lf: true, f: "Womit schützten sich Binnenburg und Butenburg gemeinsam?",
  o: ["Mit einer neuen, großen Mauer und einem breiten Wassergraben", "Mit einem Holzzaun", "Mit einer Landwehr aus Hecken", "Mit der Petersburg"],
  e: "Sie bauten eine neue, große Mauer und einen breiten Wassergraben. Daran erinnert heute die Straße „Neuer Graben“.",
  t: { x: "„… und zu ihrem Schutz bauten sie eine neue, große Mauer und einen breiten Wassergraben.“", q: "„Wie Osnabrück entstand – 3. Die Butenburg“", b: "bilder/karte_altstadt.jpg" } },
{ id: "s18", st: "stadtteile", typ: "mc", f: "Welche drei Teile bilden zusammen die Osnabrücker Altstadt?",
  o: ["Domburg, Binnenburg und Butenburg", "Binnenburg, Butenburg und Neustadt", "Domburg und Neustadt", "Nur die Binnenburg"],
  e: "Domburg + Binnenburg + Butenburg = Altstadt. Die Neustadt kam später dazu.",
  t: { x: "„Die Domburg, die Binnenburg und Butenburg bildeten zusammen die Osnabrücker Altstadt.“", q: "„Wie Osnabrück entstand – 3. Die Butenburg“" } },
{ id: "s19", st: "stadtteile", typ: "mc", lf: true, f: "Was entstand in der Neustadt?",
  o: ["Der Bischof ließ eine neue Kirche und Schulen bauen, dazu Häuser und Straßen", "Der Marktplatz und das Rathaus", "Der Dom und das Kloster", "Die Stadtwaage"],
  e: "Außerhalb der Stadtmauer ließ der Bischof die heutige Johanniskirche und Schulen bauen. Drumherum entstanden Häuser, Straßen und Wege.",
  t: { x: "„Außerhalb der Stadtmauer ließ der Bischof eine neue Kirche (die heutige Johanniskirche) erbauen und auch Schulen errichten.“", q: "„Wie Osnabrück entstand – 4. Die Neustadt“" } },
{ id: "s20", st: "stadtteile", typ: "mc", f: "Woran erkennt man die Neustadt bis heute?",
  o: ["An den breiten Straßen", "An den engen, schmalen Gassen", "Am Hafen", "An der Stadtmauer"],
  e: "Die Neustadt hat breite Straßen. In der Altstadt drängen sich die Häuser in schmalen Gassen.",
  t: { x: "„Wir erkennen sie an den breiten Straßen, während sich in der Altstadt die Häuser in den schmalen Gassen eng aneinanderdrängen.“", q: "„Osnabrück war von einer Mauer umgeben“" } },
{ id: "s21", st: "stadtteile", typ: "mc", lf: true, f: "Wie heißt die erste Kirche von Osnabrück?",
  o: ["Der Dom", "Die Marienkirche", "Die Katharinenkirche", "Die Johanniskirche"],
  e: "Der Dom. Die Bischofskirche ließ Karl der Große um 780 bauen.",
  t: { x: "„Wenn die Gebäude der Stadt Osnabrück sprechen könnten, hätte der Dom sicher am meisten zu erzählen. Denn hier, an dieser Stelle, begann die Geschichte der Stadt.“", q: "„Von der Gründung der Stadt Osnabrück“" } },
{ id: "s22", st: "stadtteile", typ: "mc", f: "Welcher Stadtteil ist auf der Karte mit A markiert?", b: "bilder/karte_abcd.jpg",
  o: ["Domburg", "Binnenburg", "Butenburg", "Neustadt"],
  e: "A ist die Domburg im Nordosten, mit dem Dom in der Mitte. Ihre Fläche ist waagerecht gestreift.",
  t: { x: "Schau in die Legende: waagerecht gestreift = Domburg, kariert = Binnenburg, senkrecht gestreift = Butenburg, fein gepunktet = Neustadt.", q: "Karte „Die Entstehung Osnabrücks im Mittelalter“", b: "bilder/karte_stadtteile.jpg" } },
{ id: "s23", st: "stadtteile", typ: "mc", f: "Welcher Stadtteil ist auf der Karte mit B markiert?", b: "bilder/karte_abcd.jpg",
  o: ["Binnenburg", "Domburg", "Butenburg", "Neustadt"],
  e: "B ist die Binnenburg, westlich der Domburg um den Markt.",
  t: { x: "Kariert = Binnenburg. Sie liegt direkt neben der Domburg.", q: "Karte „Die Entstehung Osnabrücks im Mittelalter“", b: "bilder/karte_stadtteile.jpg" } },
{ id: "s24", st: "stadtteile", typ: "mc", f: "Welcher Stadtteil ist auf der Karte mit C markiert?", b: "bilder/karte_abcd.jpg",
  o: ["Butenburg", "Binnenburg", "Domburg", "Neustadt"],
  e: "C ist die Butenburg. Sie legt sich im Westen und Süden um Dom- und Binnenburg.",
  t: { x: "Senkrecht gestreift = Butenburg, „buten“ heißt draußen.", q: "Karte „Die Entstehung Osnabrücks im Mittelalter“", b: "bilder/karte_stadtteile.jpg" } },
{ id: "s25", st: "stadtteile", typ: "mc", f: "Welcher Stadtteil ist auf der Karte mit D markiert?", b: "bilder/karte_abcd.jpg",
  o: ["Neustadt", "Butenburg", "Binnenburg", "Domburg"],
  e: "D ist die Neustadt im Süden. Sie kam um 1300 dazu.",
  t: { x: "Fein gepunktet = Neustadt. Sie liegt ganz im Süden, unten auf der Karte.", q: "Karte „Die Entstehung Osnabrücks im Mittelalter“", b: "bilder/karte_stadtteile.jpg" } },
{ id: "s26", st: "stadtteile", typ: "mc", f: "Welche Kirche ist das? Tipp: Schau auf die Türme.", b: "bilder/foto_dom.jpg",
  o: ["Der Dom", "Die Johanniskirche", "Die Marienkirche", "Die Katharinenkirche"],
  e: "Das ist der Dom: zwei Türme, die verschieden aussehen.",
  t: { x: "Merkhilfe: Der Dom hat zwei verschiedene Türme, die Johanniskirche zwei gleiche Türme, Marien- und Katharinenkirche haben je einen Turm.", q: "Foto „Was ist wo in Osnabrück?“" } },
{ id: "s27", st: "stadtteile", typ: "mc", f: "Welche Kirche ist das?", b: "bilder/foto_johanniskirche.jpg",
  o: ["Die Johanniskirche", "Der Dom", "Die Marienkirche", "Die Katharinenkirche"],
  e: "Das ist die Johanniskirche in der Neustadt: zwei gleich hohe Türme.",
  t: { x: "Merkhilfe: Der Dom hat zwei verschiedene Türme, die Johanniskirche zwei gleiche Türme.", q: "Foto „Was ist wo in Osnabrück?“" } },
{ id: "s28", st: "stadtteile", typ: "mc", f: "Welche Kirche ist das? Sie steht direkt am Marktplatz.", b: "bilder/foto_marienkirche.jpg",
  o: ["Die Marienkirche", "Die Katharinenkirche", "Der Dom", "Die Johanniskirche"],
  e: "Das ist die Marienkirche, die Kirche der Händler am Markt. Neben dem Dom ist sie die älteste Kirche der Stadt.",
  t: { x: "„An der Nordseite [des Marktplatzes] finden wir die Marienkirche, neben dem Dom die älteste Kirche unserer Stadt.“", q: "„Der Marktplatz“ und „Das Rathaus“" } },

/* ───────── Station 4: Leben in der alten Stadt ───────── */
{ id: "l1", st: "stadtleben", typ: "mc", lf: true, f: "Wie heißen diese Gebäude?", b: "bilder/fachwerk.jpg",
  o: ["Fachwerkhäuser", "Steinwerke", "Burgen", "Kirchen"],
  e: "Das sind Fachwerkhäuser: ein Gerüst aus Holzbalken, die „Fächer“ dazwischen sind mit Ziegeln oder Reisig gefüllt.",
  t: { x: "„Die Menschen bauten ihre Häuser im Fachwerkstil.“", q: "Lesetext „Die Fachwerk-Stadt“" } },
{ id: "l2", st: "stadtleben", typ: "reihe", f: "Wie baute man ein Fachwerkhaus? Bring die Schritte in die richtige Reihenfolge.",
  o: ["Gerüst und Dachstuhl aus Baumstämmen bauen", "Die „Fächer“ mit Ziegelsteinen oder Reisig füllen", "Löcher und Ritzen mit Lehm verschmieren", "Das Dach mit Holzschindeln decken"],
  e: "Erst das Holzgerüst, dann die Fächer füllen, dann mit Lehm abdichten, zuletzt das Dach decken.",
  t: { x: "„Sie errichteten mit Baumstämmen den Rohbau und den Dachstuhl eines Hauses und füllten die entstandenen „Fächer“ mit Ziegelsteinen oder Reisig auf. Die Löcher und Ritzen schmierten sie mit Lehm zu. Das Dach wurde mit Holzschindeln gedeckt.“", q: "„Die Fachwerk-Stadt“" } },
{ id: "l3", st: "stadtleben", typ: "mc", f: "Warum waren die Grundstücke in der Stadt meistens klein?",
  o: ["Der Boden in der Stadt war knapp und deshalb teuer", "Die Leute wollten kleine Gärten", "Der Bischof verbot große Häuser", "Es gab zu wenig Holz"],
  e: "Innerhalb der Mauer war wenig Platz. Grund und Boden war knapp und deshalb teuer.",
  t: { x: "„Der Grund und Boden in der Stadt war knapp und deshalb teuer.“", q: "„Die Fachwerk-Stadt“" } },
{ id: "l4", st: "stadtleben", typ: "mc", f: "Warum waren die Straßen oft dunkel und feucht?",
  o: ["Die oberen Stockwerke ragten über die Straße, kaum Sonnenlicht kam durch", "Es regnete fast jeden Tag", "Es gab keine Laternen", "Die Straßen lagen im Wald"],
  e: "Um Platz zu gewinnen, baute man die oberen Stockwerke immer weiter vor. Weil das auf beiden Straßenseiten so war, kam kaum Sonne auf die Straße.",
  t: { x: "„Um mehr Platz zu gewinnen, wurden die oberen Stockwerke immer ein Stückchen weiter vorgebaut. […] drang nur noch wenig Sonnenlicht auf die Straße durch.“", q: "„Die Fachwerk-Stadt“", b: "bilder/fachwerk.jpg" } },
{ id: "l5", st: "stadtleben", typ: "mc", f: "Was war eine große Gefahr für Fachwerkhäuser – und wer konnte sich Steinhäuser leisten?",
  o: ["Feuer – nur sehr reiche Bürger bauten aus Stein", "Hochwasser – alle Bauern", "Erdbeben – der Bischof", "Mäuse – die Händler"],
  e: "Die Holzhäuser waren immer durch Feuer gefährdet. Nur sehr reiche Bürger konnten Steinhäuser bauen.",
  t: { x: "„Diese Häuser waren immer durch Feuer gefährdet. Nur sehr reiche Bürger konnten es sich leisten, Steinhäuser zu bauen.“", q: "„Die Fachwerk-Stadt“" } },
{ id: "l6", st: "stadtleben", typ: "mc", f: "Warum wurde Osnabrück manchmal durch Feuer verwüstet?",
  o: ["Feinde schossen Feuerpfeile, und die Dächer waren aus Stroh", "Es schlug oft der Blitz ein", "Die Bürger machten zu große Lagerfeuer", "Wegen des Feuerwerks"],
  e: "Feinde schossen mit Feuerpfeilen über die Mauer, und die Häuser waren mit Stroh gedeckt. Darum baute man die Mauer höher.",
  t: { x: "„… weil die Feinde mit Feuerpfeilen über sie hinwegschießen konnten. Das war eine große Gefahr, denn die Häuser der Stadt waren mit Stroh gedeckt und fingen leicht Feuer.“", q: "Lesetext „Osnabrück war von einer Mauer umgeben“" } },
{ id: "l7", st: "stadtleben", typ: "mc", f: "Wozu wurden die großen Befestigungstürme und die Vitischanze gebaut?",
  o: ["Von dort konnten heranrückende Feinde beschossen werden", "Damit Feinde Osnabrück erobern konnten", "Als Kirchtürme", "Als Gefängnis für Diebe"],
  e: "Von den Türmen und der Vitischanze aus konnten die Osnabrücker heranrückende Gegner beschießen. Sie dienten also der Verteidigung.",
  t: { x: "„Zusätzlich wurden die großen Befestigungstürme und die Vitischanze aufgebaut, von denen die heranrückenden Gegner beschossen werden konnten.“", q: "„Osnabrück war von einer Mauer umgeben“" } },
{ id: "l8", st: "stadtleben", typ: "mc", f: "Warum waren später alle Befestigungen umsonst?",
  o: ["Mit Kanonen konnte man die Stadt aus großer Entfernung beschießen", "Die Mauer war aus Holz", "Die Feinde konnten fliegen", "Die Bürger öffneten die Tore"],
  e: "Als die Kanonen erfunden wurden, konnte man Osnabrück aus großer Entfernung beschießen. Die Stadt wurde trotzdem beschossen und besetzt.",
  t: { x: "„Als die Kanonen erfunden wurden, konnte die Stadt aus großer Entfernung beschossen werden. […] Alle Befestigungen waren umsonst.“", q: "„Osnabrück war von einer Mauer umgeben“" } },
{ id: "l9", st: "stadtleben", typ: "jahr", f: "In welchem Jahr ebneten die Osnabrücker die letzten Wälle ein und rissen Mauern und Tore ab?", a: 1872,
  e: "1872. Danach konnte Osnabrück über den alten Ring hinauswachsen und eine Großstadt werden.",
  t: { x: "„18_2 ebneten sie die letzten Wälle ein, schütteten die Gräben zu und rissen die Mauern und die engen Stadttore ab.“ (eine Ziffer versteckt)", q: "„Osnabrück war von einer Mauer umgeben“" } },
{ id: "l10", st: "stadtleben", typ: "mc", f: "Welche Straßennamen erinnern noch an die alte Stadtmauer?",
  o: ["Neuer Graben, Rolandsmauer, Schloßwall", "Bahnhofstraße, Lindenweg, Parkallee", "Domplatz, Marktstraße, Schulweg", "Hasestadion, Kinoweg, Am Zoo"],
  e: "Goethering, Schloßwall, Neuer Graben und Rolandsmauer erinnern an Wälle, Mauern und Gräben.",
  t: { x: "„Einige Straßennamen erinnern noch daran: Goethering, Schloßwall, Neuer Graben und Rolandsmauer.“", q: "„Osnabrück war von einer Mauer umgeben“" } },
{ id: "l11", st: "stadtleben", typ: "mc", f: "Was steht auf dem Marktplatz im Westen?",
  o: ["Das Rathaus", "Die Marienkirche", "Der Dom", "Die Bürgerhäuser mit Treppengiebeln"],
  e: "Im Westen das Rathaus, im Norden die Marienkirche und die Stadtwaage, im Süden die Bürgerhäuser mit Treppengiebeln.",
  t: { x: "„… sehen wir im Westen das Rathaus, im Norden erblicken wir die große Marktkirche St. Marien und die Stadtwaage und im Süden … Bürgerhäuser mit ihren Treppengiebeln.“", q: "Lesetext „Der Marktplatz – Mittelpunkt unserer Stadt“" } },
{ id: "l12", st: "stadtleben", typ: "mc", f: "Welches Gebäude ist das?", b: "bilder/foto_rathaus.jpg",
  o: ["Das Rathaus", "Der Dom", "Das Schloss", "Das Theater"],
  e: "Das ist das Osnabrücker Rathaus. Über seine Freitreppe reiten die Kinder beim Steckenpferdreiten, und drinnen ist der Friedenssaal.",
  t: { x: "„An der Westseite des Marktplatzes steht das Rathaus. Eine Freitreppe führt zum Haupteingang.“", q: "„Der Marktplatz“ und „Das Rathaus“", b: "bilder/rathaus_zeichnung.jpg" } },
{ id: "l13", st: "stadtleben", typ: "mc", f: "Warum spricht man bei diesen Häusern von Treppengiebeln?", b: "bilder/buergerhaeuser.jpg",
  o: ["Der Giebel steigt in Stufen an wie eine Treppe", "Vor jedem Haus steht eine Treppe", "Die Häuser haben eine Treppe auf dem Dach", "Man kann außen hochklettern"],
  e: "Der Giebel, also die spitze Vorderwand unter dem Dach, steigt in Stufen an wie eine Treppe.",
  t: { x: "Schau dir die Hauswände oben am Dach genau an. Wie sehen ihre Ränder aus?", q: "Foto der Bürgerhäuser am Markt" } },
{ id: "l14", st: "stadtleben", typ: "mc", f: "Wozu diente früher die Stadtwaage am Markt?",
  o: ["Dort wurde die Ware gewogen", "Dort wurden Menschen gewogen", "Dort wurde Geld gezählt", "Dort wurde Gericht gehalten"],
  e: "Auf der Stadtwaage wurde die Ware gewogen. Mit der Stadtelle maß man Tuch und Leinen.",
  t: { x: "„Auf der Stadtwaage wurde die Ware gewogen, in der Marienkirche war ein Längenmaß, die Osnabrücker Stadtelle, angebracht.“", q: "„Der Marktplatz“ und „Das Rathaus“" } },
{ id: "l15", st: "stadtleben", typ: "mc", f: "Wie nennt man den Osnabrücker Marktplatz auch?",
  o: ["Die „gute Stube“ von Osnabrück", "Die „Teufelsburg“", "Das „Friedensfeld“", "Den „Hasenplatz“"],
  e: "Der Marktplatz wird die „gute Stube“ von Osnabrück genannt.",
  t: { x: "„Er wird auch die „gute Stube“ von Osnabrück genannt.“", q: "„Der Marktplatz“ und „Das Rathaus“" } },

/* ───────── Station 5: Ablasshandel und Reformation ───────── */
{ id: "r1", st: "reformation", typ: "mc", lf: true, f: "Was ist der Ablasshandel?",
  o: ["Die Kirche verkaufte Briefe, mit denen man sich angeblich von Sünden freikaufen konnte", "Händler tauschten auf dem Markt Brot gegen Fleisch", "Man musste an der Brücke Zoll zahlen", "Die Kirche verschenkte Bibeln"],
  e: "Die Kirche bot „Ablassbriefe“ zum Kauf an. Angeblich konnten sich die Menschen damit von ihren Sünden freikaufen.",
  t: { x: "„Damals bot die Kirche „Ablassbriefe“ zum Kauf an. Angeblich konnten sich die Menschen damit von ihren Sünden freikaufen.“", q: "Nachgehakt! Ablasshandel (Reformation 4/4)" } },
{ id: "r2", st: "reformation", typ: "mc", lf: true, f: "Wie hat der Ablasshandel funktioniert?",
  o: ["Man zahlte Geld für einen Brief und glaubte, dann nicht für seine Sünden büßen zu müssen", "Man tauschte Sünden gegen Brezeln", "Der Bischof schrieb jedem kostenlos einen Brief", "Man musste dafür in den Krieg ziehen"],
  e: "Die Menschen bezahlten Geld für einen Ablassbrief. Sie glaubten, dass sie dann nach dem Tod nicht für ihre Sünden büßen mussten.",
  t: { x: "„Viele Menschen kauften solche Ablassbriefe. Denn die Menschen glaubten fest daran, nach dem Tod für ihre Sünden büßen zu müssen.“", q: "Reformation 4/4" } },
{ id: "r3", st: "reformation", typ: "mc", lf: true, f: "Warum gab es den Ablasshandel?",
  o: ["Die Menschen hatten Angst vor Strafe nach dem Tod, und die Kirche machte damit Geschäfte", "Der Kaiser hatte ihn befohlen", "Die Händler brauchten Papier", "Die Kinder sammelten die Briefe"],
  e: "Die Menschen hatten Angst, nach dem Tod büßen zu müssen. Die Kirche machte mit dieser Angst Geschäfte und verdiente Geld.",
  t: { x: "„Luther ärgerte sich, dass die Kirche mit der Angst der Menschen Geschäfte machte.“", q: "Reformation 4/4" } },
{ id: "r4", st: "reformation", typ: "mc", lf: true, f: "Wer war am Ablasshandel beteiligt – und wo gab es ihn?",
  o: ["Die Kirche verkaufte, viele Menschen kauften – in der Kirche", "Die Schweden verkauften auf dem Markt", "Luther verkaufte im Rathaus", "Die Sachsen verkauften im Wald"],
  e: "Die Kirche verkaufte die Ablassbriefe, viele Menschen kauften sie. Martin Luther kritisierte das.",
  t: { x: "„Damals bot die Kirche „Ablassbriefe“ zum Kauf an. […] Viele Menschen kauften solche Ablassbriefe.“", q: "Reformation 4/4" } },
{ id: "r5", st: "reformation", typ: "mc", f: "Wie kann man Gottes Liebe und Vergebung bekommen, sagte Luther?",
  o: ["Durch den Glauben und ein gutes Leben", "Durch viel Geld", "Durch möglichst viele Ablassbriefe", "Durch einen Krieg"],
  e: "Luther war sich sicher: Gottes Vergebung kann man nicht kaufen. Man bekommt sie durch den Glauben und ein gutes Leben.",
  t: { x: "„Jeder konnte sie erlangen: Doch nicht durch die Zahlung von Geld, sondern allein durch den Glauben und ein gutes Leben.“", q: "Reformation 4/4" } },
{ id: "r6", st: "reformation", typ: "mc", lf: true, f: "Was bedeutet das Wort „Reformation“?",
  o: ["Erneuerung", "Zerstörung", "Frieden", "Verkauf"],
  e: "Reformation bedeutet Erneuerung. Gemeint ist die Erneuerung der Kirche durch Martin Luther.",
  t: { x: "Glühbirnen-Notiz: „Reformation bedeutet ___.“ Auf dem Zeitstrahl aus dem Unterricht steht es in Klammern: „Die Reformation (E…)“.", q: "Reformation 1/4", b: "bilder/leitfragen_2.jpg" } },
{ id: "r7", st: "reformation", typ: "jahr", lf: true, f: "In welchem Jahr begann die Reformation?", a: 1517,
  e: "1517 machte Martin Luther seine 95 Vorschläge. Das war der Beginn der Reformation.",
  t: { x: "„Im Jahr 15_7 machte er 95 Vorschläge, wie sich die Kirche verändern soll.“ (eine Ziffer versteckt)", q: "Reformation 1/4" } },
{ id: "r8", st: "reformation", typ: "mc", lf: true, f: "Wer war Martin Luther?", b: "bilder/luther.jpg",
  o: ["Ein Mönch", "Ein König", "Der Bischof von Osnabrück", "Ein Gesandter aus Schweden"],
  e: "Martin Luther war ein Mönch. Er war unzufrieden mit der Kirche seiner Zeit.",
  t: { x: "„Der Mönch Martin Luther war sehr unzufrieden mit der Kirche zu seiner Zeit!“", q: "Reformation 1/4" } },
{ id: "r9", st: "reformation", typ: "wort", f: "Luther machte 95 Vorschläge. Wie nennt man sie? Die 95 …",
  a: ["Thesen", "95 Thesen"], e: "Die 95 Thesen.",
  t: { x: "Sprechblase vom Steckenpferd: „Luthers Vorschläge werden die „95 T_____“ genannt!“", q: "Reformation 1/4" } },
{ id: "r10", st: "reformation", typ: "mc", lf: true, f: "Was war der Auslöser für die Reformation? Worüber war Luther unzufrieden?",
  o: ["Papst und Bischöfe hielten sich nicht an die Bibel und lebten reich wie Fürsten", "Es gab zu wenige Kirchen", "Die Bibel war zu dick", "Die Gottesdienste waren zu kurz"],
  e: "Papst und viele Bischöfe hielten sich nicht an die Bibel und lebten in Reichtum. Am meisten ärgerte Luther der Ablasshandel.",
  t: { x: "„Damals hielten sich der Papst und viele Bischöfe nicht an die Vorgaben der Bibel. Statt wie bescheidene Kirchenmänner lebten sie in Reichtum wie Fürsten und Könige.“", q: "Reformation 1/4" } },
{ id: "r11", st: "reformation", typ: "mc", f: "Warum nannte man Luthers Anhänger „Protestanten“?",
  o: ["Weil sie gegen die Verfolgung Luthers protestierten", "Weil sie aus Preußen kamen", "Weil sie Profis waren", "Weil sie den Papst wählten"],
  e: "Papst und Kaiser ließen Luther verfolgen. Seine Anhänger protestierten dagegen und hießen deshalb Protestanten.",
  t: { x: "„Die Anhänger Luthers protestierten dagegen und erhielten daher ihren Namen: Protestanten.“", q: "Reformation 1/4" } },
{ id: "r12", st: "reformation", typ: "mc", lf: true, f: "Wer war an der Reformation beteiligt?",
  o: ["Martin Luther und seine Anhänger; Gegner waren Papst und Kaiser", "Karl der Große und Widukind", "Die Schweden und die Franzosen", "Bischof Wiho und die Sachsen"],
  e: "Martin Luther und seine Anhänger, die Protestanten. Der Papst und der Kaiser waren mächtige Gegner, weil sie um ihre Macht fürchteten.",
  t: { x: "„Er hatte viele Anhänger, aber auch mächtige Gegner. Der Papst und der Kaiser ließen Luther verfolgen, denn sie fürchteten um ihre Macht.“", q: "Reformation 1/4" } },
{ id: "r13", st: "reformation", typ: "mc", f: "Was machte Luther in seinem Versteck?",
  o: ["Er übersetzte die Bibel aus dem Lateinischen ins Deutsche", "Er schrieb Ablassbriefe", "Er baute eine Burg", "Er plante einen Krieg"],
  e: "Er übersetzte die Bibel ins Deutsche. Jetzt konnten Gottesdienste auf Deutsch gehalten werden, und alle verstanden die Bibel.",
  t: { x: "„Luther musste fliehen. In seinem Versteck übersetzte er die Bibel aus dem Lateinischen.“", q: "Reformation 1/4", b: "bilder/luther.jpg" } },
{ id: "r14", st: "reformation", typ: "mc", lf: true, f: "Wie veränderte sich das Christentum durch die Reformation?",
  o: ["Die Kirche spaltete sich in eine katholische und eine evangelische Kirche", "Alle Menschen wurden katholisch", "Es gab danach keine Kirchen mehr", "Der Papst wurde abgeschafft"],
  e: "Die Reformation führte zur Spaltung der christlichen Kirche in eine katholische und eine evangelische Kirche. Gottesdienste gab es jetzt auch auf Deutsch.",
  t: { x: "„Sie führte zu einer Spaltung der christlichen Kirche in eine katholische Kirche und eine evangelische Kirche.“", q: "Reformation 1/4" } },
{ id: "r15", st: "reformation", typ: "mc", f: "Welches Wort bedeutet dasselbe wie „protestantisch“?",
  o: ["evangelisch", "katholisch", "heidnisch", "westfälisch"],
  e: "Protestantisch und evangelisch meinen das Gleiche: die Glaubensrichtung aus der Reformation.",
  t: { x: "„Protestantisch oder evangelisch?! Beide Begriffe meinen das Gleiche …“", q: "Reformation 2/4" } },
{ id: "r16", st: "reformation", typ: "gruppen", f: "Welche Osnabrücker Kirchen blieben katholisch, welche wurden evangelisch? Wähle für jede Kirche die richtige Gruppe.",
  g: ["katholisch", "evangelisch"], i: [["Dom", 0], ["Johanniskirche", 0], ["Marienkirche", 1], ["Katharinenkirche", 1]],
  e: "Dom und Johanniskirche blieben katholisch, Marienkirche und Katharinenkirche wurden evangelisch. So ist es bis heute.",
  t: { x: "„Der Dom und die Johanniskirche blieben katholisch. Die Marienkirche und die Katharinenkirche wurden protestantisch.“", q: "Reformation 2/4", b: "bilder/waage_kirchen.jpg" } },
{ id: "r17", st: "reformation", typ: "mc", f: "Wie lebten Katholiken und Protestanten in Osnabrück nach der Reformation zusammen?",
  o: ["Meist friedlich – bis der Dreißigjährige Krieg kam", "Sie stritten jeden Tag", "Sie durften nicht in derselben Stadt wohnen", "Alle Protestanten mussten Osnabrück verlassen"],
  e: "In Osnabrück lebten sie von Anfang an meist friedlich zusammen. Das war damals etwas Besonderes. Erst der Dreißigjährige Krieg beendete das.",
  t: { x: "„In Osnabrück verlief das Zusammenleben von Katholiken und Protestanten von Anfang an meist friedlich. Das war zur damaligen Zeit etwas ganz Besonderes.“", q: "Reformation 2/4" } },
{ id: "r18", st: "reformation", typ: "mc", f: "Warum nennen sich die Protestanten „evangelisch“?",
  o: ["Sie wollen sich allein nach dem Evangelium richten", "Weil Luther Evan hieß", "Weil sie in Evangelien-Straße wohnten", "Weil der Papst es so wollte"],
  e: "Das Evangelium ist der Teil der Bibel mit den Lehren von Jesus. Danach wollen sich die Evangelischen richten, nicht nach dem Papst.",
  t: { x: "„… weil sie sich allein nach dem Evangelium richten wollen? So heißt der Teil der Bibel, in dem die Lehren von Jesus aufgeschrieben sind.“", q: "Reformation 4/4" } },

/* ───────── Station 6: Der Dreißigjährige Krieg ───────── */
{ id: "k1", st: "krieg", typ: "jahr", lf: true, f: "In welchem Jahr wurde der Augsburger Religionsfrieden beschlossen?", a: 1555,
  e: "1555 in Augsburg.",
  t: { x: "„So war es im Jahr 15_5 im Augsburger Religionsfrieden ausgemacht worden.“ (eine Ziffer versteckt)", q: "Dreißigjähriger Krieg 1/5" } },
{ id: "k2", st: "krieg", typ: "mc", lf: true, f: "Was ist der Augsburger Religionsfrieden?",
  o: ["Ein Vertrag: Katholiken und Protestanten sind gleichberechtigt, keiner darf dem anderen seine Religion aufzwingen", "Ein Vertrag, dass alle katholisch werden müssen", "Ein Fest in Augsburg", "Der Vertrag, der den Dreißigjährigen Krieg beendete"],
  e: "Er legte die Gleichberechtigung von Protestanten und Katholiken fest. Er hielt mehr als 60 Jahre lang den Frieden.",
  t: { x: "„Er legte die Gleichberechtigung von Protestanten und Katholiken fest. Keine Seite durfte der anderen die eigene Religion aufzwingen.“", q: "Nachgehakt! Augsburger Religionsfrieden (Krieg 5/5)" } },
{ id: "k3", st: "krieg", typ: "mc", lf: true, f: "Wer hat den Augsburger Religionsfrieden beschlossen?",
  o: ["Der Kaiser und die protestantischen Fürsten", "Martin Luther und der Papst", "Die Schweden und die Franzosen", "Der Bürgermeister von Osnabrück"],
  e: "Der Kaiser und die protestantischen Fürsten schlossen ihn 1555 in Augsburg.",
  t: { x: "„Um Frieden zwischen Katholiken und Protestanten zu halten, schlossen der Kaiser und die protestantischen Fürsten im Jahr 1555 in Augsburg den sogenannten Augsburger Religionsfrieden.“", q: "Krieg 5/5" } },
{ id: "k4", st: "krieg", typ: "mc", f: "Für wen galt die Religionsfreiheit im Augsburger Religionsfrieden?",
  o: ["Nur für die Fürsten – das Volk musste die Religion seines Herrn annehmen", "Für alle Menschen", "Nur für Kinder", "Nur für die Stadt Osnabrück"],
  e: "Nur die Fürsten konnten wählen. Die einfachen Leute mussten die Religion ihres Herrn annehmen oder auswandern.",
  t: { x: "„Diese Religionsfreiheit galt aber nur für die Fürsten. Die einfache Bevölkerung hatte keine Wahl: Sie musste die Religion ihres Herrn annehmen.“", q: "Krieg 5/5" } },
{ id: "k5", st: "krieg", typ: "mc", f: "Was ist eine Konfession?",
  o: ["Eine Glaubensrichtung innerhalb einer Religion", "Ein anderes Wort für Kirche", "Ein Friedensvertrag", "Ein Gebet"],
  e: "Katholiken und Protestanten haben die gleiche Religion (Christen), aber unterschiedliche Konfessionen.",
  t: { x: "„Eine Konfession ist eine Glaubensrichtung innerhalb einer Religion.“", q: "Krieg 1/5" } },
{ id: "k6", st: "krieg", typ: "mc", f: "Was wollte der neue Kaiser im Jahr 1618?",
  o: ["Die Reformation rückgängig machen – alle sollten wieder katholisch werden", "Dass alle evangelisch werden", "Frieden mit allen schließen", "Nach Osnabrück ziehen"],
  e: "Der Kaiser hielt sich nicht mehr an den Augsburger Religionsfrieden. Das ganze Reich sollte wieder katholisch werden.",
  t: { x: "„Der neue Kaiser hielt sich nicht mehr an die Abmachungen. Er wollte die Reformation rückgängig machen: Das ganze Reich sollte wieder katholisch werden.“", q: "Krieg 1/5" } },
{ id: "k7", st: "krieg", typ: "jahr", lf: true, f: "In welchem Jahr war der Prager Fenstersturz?", a: 1618,
  e: "1618. Damit begann der Dreißigjährige Krieg.",
  t: { x: "Er war der Auslöser des Dreißigjährigen Krieges – also im ersten Kriegsjahr. „Ein einziges Ereignis im Jahr 16_8 reichte aus …“", q: "Krieg 1/5", b: "bilder/fenstersturz.jpg" } },
{ id: "k8", st: "krieg", typ: "mc", lf: true, f: "Wo ist der Fenstersturz passiert?", b: "bilder/fenstersturz.jpg",
  o: ["In Prag, im Königreich Böhmen", "In Osnabrück", "In Münster", "In Augsburg"],
  e: "In Prag im Königreich Böhmen, in der königlichen Burg.",
  t: { x: "Der Name verrät es schon: der „Prag-er“ Fenstersturz. „Im kleinen Königreich Böhmen …“", q: "Krieg 1/5" } },
{ id: "k9", st: "krieg", typ: "mc", lf: true, f: "Wer war am Prager Fenstersturz beteiligt?",
  o: ["Evangelische Adelige warfen die Verwalter des katholischen Königs aus dem Fenster", "Der Kaiser warf Luther aus dem Fenster", "Schwedische Soldaten warfen den Bischof hinaus", "Kinder warfen Steckenpferde aus dem Fenster"],
  e: "Die evangelischen Adeligen stürmten die königliche Burg und warfen die Verwalter des Königs zum Fenster hinaus.",
  t: { x: "„Sie stürmten die königliche Burg in Prag und warfen die Verwalter des Königs einfach zum Fenster hinaus.“", q: "Krieg 1/5" } },
{ id: "k10", st: "krieg", typ: "mc", lf: true, f: "Warum ist der Fenstersturz passiert?",
  o: ["Der katholische König unterdrückte die Protestanten", "Es ging um einen Streit über Geld", "Die Verwalter wollten fliegen lernen", "Es war ein Unfall"],
  e: "Der Kaiser hatte in Böhmen einen katholischen König eingesetzt, der die Protestanten unterdrückte. Das wollten die evangelischen Adeligen nicht hinnehmen.",
  t: { x: "„Dieser war katholisch und unterdrückte die Protestanten. Das wollten sich die evangelischen Adeligen nicht gefallen lassen.“", q: "Krieg 1/5" } },
{ id: "k11", st: "krieg", typ: "mc", f: "Was passierte mit den Verwaltern, die aus dem Fenster fielen?",
  o: ["Sie fielen weich auf einen Misthaufen und überlebten", "Sie landeten in der Moldau", "Sie flogen bis nach Osnabrück", "Sie wurden zu Bischöfen"],
  e: "Unter dem Fenster lag ein Misthaufen. Die Verwalter kamen mit dem Schrecken davon.",
  t: { x: "„Übrigens: Die königlichen Verwalter kamen mit dem Schrecken davon. Sie fielen weich, denn unter dem Fenster lag ein …“", q: "Krieg 1/5" } },
{ id: "k12", st: "krieg", typ: "jahr", lf: true, f: "In welchem Jahr endete der Dreißigjährige Krieg?", a: 1648,
  e: "1648. Er dauerte von 1618 bis 1648, also 30 Jahre.",
  t: { x: "Er begann 1618 und dauerte 30 Jahre. Rechne: 1618 + 30 = ?", q: "Krieg 2/5" } },
{ id: "k13", st: "krieg", typ: "gruppen", lf: true, f: "Wer kämpfte gegen wen? Wähle für jede Kriegspartei die richtige Seite.", b: "bilder/fahnentraeger.jpg",
  g: ["katholische Seite", "protestantische Seite"],
  i: [["der Kaiser", 0], ["die katholischen Fürsten", 0], ["Spanien", 0], ["die protestantischen Fürsten", 1], ["Dänemark", 1], ["Schweden", 1], ["Frankreich", 1]],
  e: "Katholisch: Kaiser, katholische Fürsten, Spanien. Protestantisch: protestantische Fürsten, Dänemark, Schweden. Das katholische Frankreich half den Protestanten!",
  t: { x: "„Auf katholischer Seite kämpften der mächtige Kaiser, die katholischen Fürsten und Spanien. Das protestantische Lager bestand aus den protestantischen Fürsten und den protestantischen Ländern Dänemark und Schweden. Doch auch das katholische Frankreich unterstützte die Protestanten.“", q: "Die Kriegsparteien (Krieg 4/5)" } },
{ id: "k14", st: "krieg", typ: "mc", f: "Das katholische Frankreich half den Protestanten. Was zeigt das?",
  o: ["Es ging nicht nur um den Glauben, sondern auch um Macht", "Frankreich war eigentlich evangelisch", "Frankreich hat sich verirrt", "Die Protestanten haben Frankreich bezahlt"],
  e: "Wenn ein katholisches Land den Protestanten hilft, geht es offensichtlich nicht nur um den „richtigen“ Glauben, sondern um Macht.",
  t: { x: "„Dies zeigt: Im Dreißigjährigen Krieg ging es längst nicht nur um den „richtigen“ Glauben.“", q: "Krieg 4/5" } },
{ id: "k15", st: "krieg", typ: "mc", lf: true, f: "Worum ging es im Dreißigjährigen Krieg?",
  o: ["Um den „richtigen“ Glauben und um die Macht in Deutschland und Europa", "Nur um die Hase", "Um ein Fußballspiel", "Um den Ablasshandel"],
  e: "Am Anfang war es ein Religionskrieg. In Wirklichkeit ging es auch darum, wer am meisten Macht in Europa bekam.",
  t: { x: "„Katholische und protestantische Herrscher kämpften miteinander um den „richtigen“ Glauben und die Vorherrschaft in Deutschland und Europa.“", q: "Merkkasten Krieg 2/5" } },
{ id: "k16", st: "krieg", typ: "mc", f: "Wie ging es den Menschen während des Krieges?",
  o: ["Soldaten raubten Essen, Vieh und Wohnungen, es gab viel Gewalt", "Sie merkten nichts vom Krieg", "Sie bekamen jeden Tag Geschenke", "Alle zogen nach Amerika"],
  e: "30 Jahre Not und Elend: Soldatenheere raubten alles. Viele Menschen erlebten ihr ganzes Leben nur Krieg.",
  t: { x: "„Soldatenheere zogen durch das Land. Sie raubten den Menschen all ihr Hab und Gut: ihre Lebensmittel, ihr Vieh und ihre Wohnungen.“", q: "Krieg 2/5", b: "bilder/kriegstraum.jpg" } },
{ id: "k17", st: "krieg", typ: "mc", f: "Wie kann man Streit auf friedlichem Weg lösen?",
  o: ["Miteinander reden, Kompromisse schließen oder jemanden um Vermittlung bitten", "Einfach weglaufen", "Den Stärkeren gewinnen lassen", "Gar nicht"],
  e: "Kriege können verhindert werden: durch Reden, Kompromisse und Vermittlung. Genau so wurde später auch der Dreißigjährige Krieg beendet.",
  t: { x: "„… indem man miteinander redet, Kompromisse schließt oder jemanden um Vermittlung bittet.“", q: "Muss es Kriege geben? (Krieg 5/5)" } },

/* ───────── Station 7: Der Westfälische Friede ───────── */
{ id: "w1", st: "frieden", typ: "mc", lf: true, f: "Was ist der Westfälische Frieden?",
  o: ["Der Friedensvertrag, der den Dreißigjährigen Krieg beendete", "Ein Fest in Münster", "Der Vertrag von 1555", "Ein Gedicht von Luther"],
  e: "Der Westfälische Frieden beendete 1648 den Dreißigjährigen Krieg. Zum ersten Mal wurde ein Krieg durch Verhandlungen beendet.",
  t: { x: "„Am 24. Oktober 1648 trafen alle Gesandten in Münster zusammen und unterzeichneten den Westfälischen Frieden. Damit fand ein langer, schrecklicher Krieg endlich ein Ende.“", q: "Der Westfälische Friede 1/3" } },
{ id: "w2", st: "frieden", typ: "jahr", lf: true, f: "In welchem Jahr wurde der Westfälische Frieden geschlossen?", a: 1648,
  e: "1648, im selben Jahr endete der Dreißigjährige Krieg.",
  t: { x: "Der Frieden beendete den Krieg von 1618 bis …", q: "Frieden 1/3" } },
{ id: "w3", st: "frieden", typ: "paare", lf: true, f: "Was geschah an welchem Tag? Verbinde.",
  p: [["24. Oktober 1648", "in Münster unterzeichnet"], ["25. Oktober 1648", "in Osnabrück verkündet"]],
  e: "Am 24. Oktober 1648 wurde in Münster unterzeichnet, am 25. Oktober verkündete der Bürgermeister den Frieden in Osnabrück.",
  t: { x: "„Am 24. Oktober 1648 trafen alle Gesandten in Münster zusammen und unterzeichneten … In Osnabrück verkündete der Bürgermeister den Frieden am 25. Oktober 1648 von der Rathaustreppe.“", q: "Frieden 1/3" } },
{ id: "w4", st: "frieden", typ: "mc", lf: true, f: "Wer verkündete den Frieden in Osnabrück – und wo?",
  o: ["Der Bürgermeister, von der Rathaustreppe", "Der Bischof, vom Domturm", "Der Kaiser, vom Schloss", "Martin Luther, aus der Marienkirche"],
  e: "Der Bürgermeister verkündete den Frieden am 25. Oktober 1648 von der Rathaustreppe.",
  t: { x: "„In Osnabrück verkündete der Bürgermeister den Frieden am 25. Oktober 1648 von der Rathaustreppe.“", q: "Frieden 1/3", b: "bilder/rathaus_zeichnung.jpg" } },
{ id: "w5", st: "frieden", typ: "mc", lf: true, f: "Wo wurde über den Frieden verhandelt?",
  o: ["In Osnabrück und Münster", "In Prag und Augsburg", "Nur in Nürnberg", "In Paris"],
  e: "In zwei Städten: im evangelischen Osnabrück und im katholischen Münster.",
  t: { x: "„In den Friedensverträgen von Osnabrück und Münster wurden Lösungen für alle wichtigen Streitpunkte gefunden.“", q: "Frieden 1/3" } },
{ id: "w6", st: "frieden", typ: "mc", f: "Warum wurde in zwei Städten verhandelt?",
  o: ["Die Katholiken wollten einen katholischen Ort (Münster), die Protestanten einen evangelischen (Osnabrück)", "Eine Stadt war zu klein für alle Pferde", "Es regnete in Münster", "Der Kaiser wohnte in beiden"],
  e: "So wählte man ein „Städtepaar“: das evangelische Osnabrück und das katholische Münster. Reitende Boten schafften den Weg an einem Tag.",
  t: { x: "„Die Katholiken verlangten einen katholischen Verhandlungsort, die Protestanten einen evangelischen. So fiel die Wahl auf ein „Städtepaar“: das evangelische Osnabrück und das katholische Münster.“", q: "Der Friedenskongress 1/4 (Stadt)" } },
{ id: "w7", st: "frieden", typ: "mc", f: "Wie lange wurde verhandelt?",
  o: ["Fünf Jahre, von 1643 bis 1648", "Fünf Tage", "Ein Jahr", "Dreißig Jahre"],
  e: "Fünf lange Jahre, von 1643 bis 1648.",
  t: { x: "„Nach fünf langen Verhandlungsjahren waren endlich alle Streitfragen geklärt.“", q: "Frieden 1/3" } },
{ id: "w8", st: "frieden", typ: "mc", lf: true, f: "Wer war am Westfälischen Frieden beteiligt?",
  o: ["Gesandte aller Kriegsparteien aus ganz Europa", "Nur die Osnabrücker Bürger", "Nur der Papst", "Die Kinder mit ihren Steckenpferden"],
  e: "Die Kriegsparteien schickten Gesandte aus ganz Europa nach Osnabrück und Münster. In Osnabrück verkündete der Bürgermeister den Frieden.",
  t: { x: "„Gesandte aus ganz Europa trafen sich in Osnabrück und Münster, um den 30-jährigen Krieg zu beenden.“", q: "Friedenskongress 2/4 (Stadt)", b: "bilder/gesandte.jpg" } },
{ id: "w9", st: "frieden", typ: "mc", f: "Was ist ein Gesandter?",
  o: ["Ein Vertreter, den ein Staat oder Herrscher schickt – heute sagt man Botschafter", "Ein Postbote", "Ein Soldat", "Ein Pfarrer"],
  e: "Ein Gesandter wird von einem Staat oder Herrscher als Vertreter geschickt („gesandt“). Heute sagen wir Botschafter oder Diplomat.",
  t: { x: "„Gesandter: ein Gesandter wird von einem Staat oder Herrscher als Interessensvertreter geschickt („gesandt“). Heute sprechen wir von Botschaftern oder Diplomaten.“", q: "Friedenskongress 1/4 (Stadt)", b: "bilder/m_gesandter.png" } },
{ id: "w10", st: "frieden", typ: "mehrfach", lf: true, f: "Was wurde im Westfälischen Frieden beschlossen? Tippe ALLE richtigen Punkte an.",
  o: ["Der Kaiser musste Macht an die Fürsten abgeben", "Die Herrschaft über viele Gebiete wurde neu verteilt", "Alle christlichen Konfessionen erhielten die gleichen Rechte", "Die Menschen mussten nicht mehr die Religion ihres Herrschers annehmen", "Alle mussten wieder katholisch werden", "Osnabrück wurde Hauptstadt von Europa"],
  r: [0, 1, 2, 3],
  e: "Vier Punkte: Kaiser gibt Macht ab, Gebiete neu verteilt, gleiche Rechte für alle christlichen Konfessionen, keine Pflicht mehr zur Religion des Herrschers.",
  t: { x: "Auf der Vertragsrolle stehen vier Häkchen. Sie handeln vom Kaiser, von Gebieten, von den Konfessionen und von der Religion der Menschen.", q: "Frieden 1/3" } },
{ id: "w11", st: "frieden", typ: "mc", f: "Warum war der Westfälische Frieden etwas ganz Besonderes?",
  o: ["Zum ersten Mal wurde ein Krieg durch Verhandlungen beendet", "Er war der kürzeste Vertrag der Welt", "Er wurde von Kindern geschrieben", "Er wurde in Osnabrück und auf dem Mond gefeiert"],
  e: "Nie zuvor hatte es einen großen europäischen Friedenskongress gegeben, nie zuvor war ein Krieg durch Verhandlungen beendet worden. Er wurde ein Vorbild bis heute.",
  t: { x: "„Erstmals wurde ein langer, schrecklicher Krieg durch Verhandlungen beendet.“", q: "Merkkasten Frieden 1/3" } },
{ id: "w12", st: "frieden", typ: "mc", f: "Warum nennt sich Osnabrück „die Friedensstadt“?",
  o: ["Weil Osnabrück beim Westfälischen Frieden eine wichtige Rolle spielte", "Weil es dort nie Streit gab", "Weil Karl der Große es so nannte", "Weil dort ein Friedhof ist"],
  e: "Osnabrück war einer der beiden Verhandlungsorte des Westfälischen Friedens.",
  t: { x: "„Weil Osnabrück dabei eine wichtige Rolle spielte, nennen wir uns stolz „die Friedensstadt“.“", q: "Frieden 1/3" } },
{ id: "w13", st: "frieden", typ: "mc", f: "Was bedeutet „Pacificatores“?",
  o: ["Friedensmacher", "Pferdereiter", "Kriegsherren", "Brezelbäcker"],
  e: "Pacificatores ist Latein und heißt Friedensmacher. Im Friedenssaal hängen Bilder von 42 der 150 Friedensmacher.",
  t: { x: "„Im Friedenssaal sind 42 der insgesamt 150 „Pacificatores“ zu sehen. In der lateinischen Sprache bedeutet das „F…“.“", q: "Der Friedenssaal (Frieden 3/3)" } },
{ id: "w14", st: "frieden", typ: "mc", f: "Was hängt an den Wänden des Friedenssaals im Rathaus?",
  o: ["Bilder der Herrscher und Gesandten, die am Frieden mitgewirkt haben", "Waffen aus dem Krieg", "Steckenpferde", "Landkarten von Amerika"],
  e: "Gemälde der Herrscher und Gesandten. Man soll sich immer an den Frieden erinnern.",
  t: { x: "„An den Wänden hängen die Gemälde der Herrscher und Gesandten, die am Westfälischen Frieden mitgewirkt haben.“", q: "Frieden 3/3" } },
{ id: "w15", st: "frieden", typ: "mc", f: "Warum heißt er „Westfälischer“ Frieden?",
  o: ["Osnabrück und Münster gehörten damals zur Region Westfalen", "Weil er im Westen von Falen geschlossen wurde", "Weil die Gesandten Falken hatten", "Weil es im Westen war"],
  e: "Osnabrück und Münster gehörten zur Region Westfalen. Heute liegt Münster in Nordrhein-Westfalen und Osnabrück in Niedersachsen.",
  t: { x: "„… weil die Städte Osnabrück und Münster damals zur Region „Westfalen“ gehörten?“", q: "Frieden 3/3" } },
{ id: "w16", st: "frieden", typ: "mc", f: "Wie kamen die Nachrichten zwischen Osnabrück und Münster hin und her?",
  o: ["Mit reitenden Boten", "Per Telefon", "Mit dem Zug", "Mit Brieftauben"],
  e: "Reitende Boten brachten die Nachrichten innerhalb eines Tages von Stadt zu Stadt.",
  t: { x: "„Reitende Boten konnten wichtige Botschaften innerhalb eines Tages überbringen.“", q: "Friedenskongress 1/4 (Stadt)", b: "bilder/postroute.jpg" } },

/* ───────── Station 8: Das Steckenpferdreiten ───────── */
{ id: "p1", st: "steckenpferd", typ: "mc", lf: true, f: "Was ist das Steckenpferdreiten?",
  o: ["Alle 4. Klassen ziehen mit selbstgebastelten Steckenpferden durch die Stadt und reiten über die Rathaustreppe", "Ein Pferderennen auf echten Pferden", "Ein Basteltag in der Schule", "Ein Umzug mit Kutschen"],
  e: "Jedes Jahr ziehen alle Kinder der 4. Klassen mit selbstgebastelten Steckenpferden durch die Innenstadt und reiten über die Rathaustreppe. Danach gibt es ein Friedensfest.",
  t: { x: "„Jedes Jahr am 25. Oktober ziehen alle Kinder der 4. Klassen von Osnabrück mit ihren selbstgebastelten Steckenpferden durch die Innenstadt.“", q: "Das Steckenpferdreiten 1/3 (Stadt)", b: "bilder/brunnen.jpg" } },
{ id: "p2", st: "steckenpferd", typ: "mc", lf: true, f: "Warum wird das Steckenpferdreiten heute in Osnabrück gefeiert?",
  o: ["Zur Erinnerung an die Verkündung des Westfälischen Friedens", "Zum Geburtstag von Karl dem Großen", "Weil die Hase Geburtstag hat", "Zum Ende der Sommerferien"],
  e: "Die Kinder erinnern an die Verkündung des Westfälischen Friedens am 25. Oktober 1648 von der Rathaustreppe. Sie sind Botschafter für den Frieden.",
  t: { x: "„In Osnabrück verkündete der Bürgermeister den Frieden am 25. Oktober 1648 von der Rathaustreppe. Darum feiern wir Osnabrücker noch heute an diesem Tag ein großes Friedensfest – das Steckenpferdreiten.“", q: "Frieden 1/3" } },
{ id: "p3", st: "steckenpferd", typ: "mc", lf: true, f: "Woher kommt die Tradition des Steckenpferdreitens?",
  o: ["Aus einer Geschichte von 1650 in Nürnberg", "Aus Prag", "Von Karl dem Großen", "Aus Münster im Jahr 1555"],
  e: "1650 ritten in Nürnberg Jungen mit Steckenpferden zum Fürsten Piccolomini. Die Dichterinnen Clara und Emmy von Dincklage verlegten die Geschichte 1875 nach Osnabrück.",
  t: { x: "„Der Brauch geht auf eine Geschichte zurück, die sich im Jahr 1650 in der Stadt Nürnberg ereignet hat.“", q: "Steckenpferdreiten 1/3 (Stadt)", b: "bilder/leitfragen_2.jpg" } },
{ id: "p4", st: "steckenpferd", typ: "jahr", lf: true, f: "In welchem Jahr ritten die Nürnberger Jungen mit ihren Steckenpferden zum Fürsten?", a: 1650,
  e: "1650, zwei Jahre nach dem Westfälischen Frieden. Auf dem Zeitstrahl aus dem Unterricht steht 1650 ganz am Ende.",
  t: { x: "Zwei Jahre nach dem Westfälischen Frieden (1648). Auf dem Zeitstrahl aus dem Unterricht ist es die letzte Zahl.", q: "Steckenpferdreiten 1/3 und Zeitstrahl aus dem Unterricht", b: "bilder/leitfragen_2.jpg" } },
{ id: "p5", st: "steckenpferd", typ: "mc", f: "Zu wem ritten die Nürnberger Kinder?",
  o: ["Zum Fürsten Piccolomini, einem Gesandten des Kaisers", "Zu Martin Luther", "Zum Bürgermeister von Osnabrück", "Zu Karl dem Großen"],
  e: "Zum Fürsten Piccolomini, einem Gesandten des Kaisers. Sie baten ihn um ein Andenken an den Frieden.",
  t: { x: "„Dort hielt sich damals der Fürst Piccolomini auf, ein Gesandter des Kaisers. Es wird berichtet, dass die Jungen von Nürnberg mit ihren Steckenpferden zu ihm geritten sind.“", q: "Steckenpferdreiten 1/3" } },
{ id: "p6", st: "steckenpferd", typ: "mc", f: "Was schenkte der Fürst den Kindern?",
  o: ["Kleine silberne Gedenkmünzen mit einem Steckenpferdreiter", "Brezeln", "Echte Pferde", "Ablassbriefe"],
  e: "Silberne Gedenkmünzen, darauf ein Steckenpferdreiter. Eine davon liegt heute in der Schatzkammer des Osnabrücker Rathauses.",
  t: { x: "„Er ließ kleine silberne Gedenkmünzen anfertigen und schenkte sie den Kindern. Was auf den Münzen zu sehen ist? Natürlich ein Steckenpferdreiter!“", q: "Steckenpferdreiten 1/3" } },
{ id: "p7", st: "steckenpferd", typ: "mc", f: "Wer brachte die Geschichte der Steckenpferdreiter nach Osnabrück?",
  o: ["Die Dichterinnen Clara und Emmy von Dincklage", "Fürst Piccolomini", "Martin Luther", "Bischof Wiho"],
  e: "Clara und Emmy von Dincklage schrieben die Geschichte 1875 auf und ließen sie in Osnabrück spielen. So wurde sie eine Osnabrücker Sage.",
  t: { x: "„Das verdanken wir den beiden Dichterinnen Clara und Emmy von Dincklage. […] Dabei „schummelten“ sie ein wenig und ließen die Geschichte in Osnabrück spielen.“", q: "Steckenpferdreiten 1/3" } },
{ id: "p8", st: "steckenpferd", typ: "jahr", f: "In welchem Jahr schrieben die Dichterinnen die Geschichte auf?", a: 1875,
  e: "1875.", t: { x: "„… dass sie sie im Jahr 18_5 aufschrieben.“ (eine Ziffer versteckt)", q: "Steckenpferdreiten 1/3" } },
{ id: "p9", st: "steckenpferd", typ: "jahr", f: "In welchem Jahr fand das erste Osnabrücker Steckenpferdreiten statt?", a: 1948,
  e: "1948 ritten zum ersten Mal Osnabrücker Kinder über die Rathaustreppe, genau 300 Jahre nach dem Westfälischen Frieden. Seit 1953 findet es jedes Jahr statt.",
  t: { x: "Genau 300 Jahre nach dem Westfälischen Frieden (1648). Rechne: 1648 + 300 = ?", q: "Steckenpferdreiten 3/3 (Stadt)" } },
{ id: "p10", st: "steckenpferd", typ: "mc", f: "Was schenkt der Bürgermeister jedem Kind beim Steckenpferdreiten?",
  o: ["Eine süße Brezel", "Ein echtes Pferd", "Eine Gedenkmünze", "Ein Buch"],
  e: "Der Bürgermeister begrüßt die Steckenpferdreiter persönlich und schenkt jedem Kind eine süße Brezel.",
  t: { x: "„Der Bürgermeister persönlich begrüßt die Steckenpferdreiter und schenkt jedem Kind eine süße …“", q: "Steckenpferdreiten 1/3" } },
{ id: "p11", st: "steckenpferd", typ: "mc", f: "Über was reiten die Kinder am Marktplatz?",
  o: ["Über die Rathaustreppe", "Über die Domtreppe", "Über die Hasebrücke", "Über die Stadtmauer"],
  e: "Über die Rathaustreppe, also genau dort, wo 1648 der Frieden verkündet wurde.",
  t: { x: "„Am Marktplatz angekommen reiten alle Kinder über die …“", q: "Steckenpferdreiten 1/3" } },
{ id: "p12", st: "steckenpferd", typ: "mc", f: "Wer durfte beim ersten Steckenpferdreiten 1948 reiten?",
  o: ["Nur die Jungen – die Mädchen trugen Laternen", "Nur die Mädchen", "Alle Kinder und Erwachsenen", "Nur die Lehrer"],
  e: "Damals ritten nur die Jungen, die Mädchen trugen Laternen. Erst seit den 1970er Jahren reiten auch Mädchen mit.",
  t: { x: "„Damals durften aber nur die Jungen auf Steckenpferden reiten, die Mädchen trugen Laternen.“", q: "Steckenpferdreiten 3/3" } },
{ id: "p13", st: "steckenpferd", typ: "mc", f: "Was ist damit gemeint: Kinder sollen „Botschafter für den Frieden“ sein?",
  o: ["Die Kinder erinnern alle Menschen daran, wie wichtig Frieden ist", "Die Kinder tragen Briefe aus", "Die Kinder fahren nach Münster", "Die Kinder werden Gesandte"],
  e: "Mit dem Steckenpferdreiten erinnern die Kinder alle daran, wie wichtig Frieden ist. Nie wieder sollte es Krieg geben.",
  t: { x: "„In diesem Jahr ist auch deine Schulklasse dabei und erinnert alle Menschen daran, wie wichtig Frieden ist.“", q: "Steckenpferdreiten 1/3" } },
{ id: "p14", st: "steckenpferd", typ: "mc", f: "Wo steht dieser Steckenpferdreiter-Brunnen?", b: "bilder/brunnen.jpg",
  o: ["An der Katharinenkirche", "Am Dom", "Am Hauptbahnhof", "In Münster"],
  e: "Der Steckenpferdreiter-Brunnen steht an der Katharinenkirche.",
  t: { x: "Bildunterschrift: „Steckenpferdreiter-Brunnen an der K…kirche“", q: "Steckenpferdreiten 2/3" } },

/* ───────── Zeitstrahl-Training ───────── */
{ id: "z1", st: "zeit", typ: "reihe", f: "Von der Steinzeit bis zur Neustadt: Bring diese Ereignisse in die richtige zeitliche Reihenfolge.",
  o: ["Jäger leben im Osnabrücker Land", "Germanen kommen aus dem Norden", "Karl der Große lässt die Bischofskirche bauen", "Die Binnenburg entsteht", "Die Neustadt entsteht"],
  e: "4000–2000 v. Chr. Jäger → um 1000 v. Chr. Germanen → um 780 Bischofskirche → um 1000 Binnenburg → um 1300 Neustadt.",
  t: { x: "Schau auf das Übersichtsblatt aus dem Unterricht: Der Zeitstrahl beginnt bei 4000 v. Chr. und endet bei 1300.", q: "Übersichtsblatt aus dem Unterricht", b: "bilder/leitfragen_1.jpg" } },
{ id: "z2", st: "zeit", typ: "reihe", f: "Von Luther bis Nürnberg: Bring diese Ereignisse in die richtige zeitliche Reihenfolge.",
  o: ["Reformation (Luthers 95 Thesen)", "Augsburger Religionsfrieden", "Prager Fenstersturz", "Westfälischer Frieden", "Steckenpferdreiter in Nürnberg"],
  e: "1517 Reformation → 1555 Religionsfrieden → 1618 Fenstersturz → 1648 Westfälischer Frieden → 1650 Nürnberg.",
  t: { x: "Der Zeitstrahl aus dem Unterricht: 1517 – 1555 – 1600 – 1618 – 1648 – 1650.", q: "Zeitstrahl aus dem Unterricht", b: "bilder/leitfragen_2.jpg" } },
{ id: "z3", st: "zeit", typ: "paare", f: "Welches Jahr gehört zu welchem Ereignis? Verbinde.",
  p: [["Reformation", "1517"], ["Augsburger Religionsfrieden", "1555"], ["Prager Fenstersturz", "1618"], ["Westfälischer Frieden", "1648"]],
  e: "1517 – 1555 – 1618 – 1648. Diese vier Zahlen solltest du sicher können!",
  t: { x: "Reihenfolge: erst Luther, dann der Religionsfrieden, dann der Fenstersturz, zum Schluss der Frieden.", q: "Zeitstrahl aus dem Unterricht", b: "bilder/leitfragen_2.jpg" } },
{ id: "z4", st: "zeit", typ: "jahr", f: "Wie viele Jahre dauerte der Dreißigjährige Krieg? (Tipp: Der Name verrät es.)", a: 30,
  e: "30 Jahre, von 1618 bis 1648.", t: { x: "Dreißig-jährig …", q: "Krieg 2/5" } },
{ id: "z5", st: "zeit", typ: "jahr", f: "Wie viele Jahre wurde über den Westfälischen Frieden verhandelt?", a: 5,
  e: "5 Jahre, von 1643 bis 1648.", t: { x: "„Nach fünf langen Verhandlungsjahren …“ – als Zahl!", q: "Frieden 1/3" } },
{ id: "z6", st: "zeit", typ: "jahr", f: "Wie viele Vorschläge (Thesen) schrieb Martin Luther?", a: 95,
  e: "95 Thesen.", t: { x: "„Im Jahr 1517 machte er __ Vorschläge …“", q: "Reformation 1/4" } },

/* ───────── Probearbeit: die Leitfragen aus dem Unterricht zum Selbst-Erklären ───────── */
{ id: "q1", st: "probe", typ: "erklaer", f: "Warum entstand Osnabrück gerade an dieser Stelle? Nenne zwei Gründe.",
  k: ["Furt: flache Stelle in der Hase zum Überqueren", "Hügel kamen nah an den Fluss, später Brücke", "Kreuzung alter Handelswege"],
  m: "1. Grund: Dort gab es eine Furt, eine flache Stelle, an der man die Hase leicht überqueren konnte; später wurde dort eine Brücke gebaut. 2. Grund: Hier kreuzten sich alte Handelswege von Süden nach Norden und von Westen nach Osten." },
{ id: "q2", st: "probe", typ: "erklaer", f: "Wie entstand Osnabrück? Wer lebte hier, und was passierte im Jahr 780?",
  k: ["Die Sachsen lebten hier (Heiden, viele Götter)", "Karl der Große besiegte die Sachsen (Widukind)", "780: Bischofskirche an der Furt gebaut", "Wiho wurde erster Bischof"],
  m: "Im Osnabrücker Land lebten die Sachsen. Karl der Große, König der Franken, besiegte sie und ihren Herzog Widukind. Um 780 ließ er an der Furt eine Bischofskirche bauen und setzte Wiho als ersten Bischof ein, der die Sachsen zu Christen machen sollte." },
{ id: "q3", st: "probe", typ: "erklaer", f: "Die Domburg: Was entstand dort, wie hieß die Kirche, und wie war sie geschützt?",
  k: ["Dom, Kloster, Schule (Carolinum)", "Häuser für Priester, Kornspeicher, Ställe", "Kirche: der Dom", "Schutz: starker Zaun"],
  m: "In der Domburg entstanden der Dom, ein Kloster, eine Schule (das heutige Carolinum), Häuser für die Priester, Kornspeicher und Ställe. Geschützt war sie durch einen starken Zaun." },
{ id: "q4", st: "probe", typ: "erklaer", f: "Die Binnenburg (um 1000): Was entstand dort, wie hieß die Kirche, und wie war sie geschützt?",
  k: ["Häuser und Gassen um den Marktplatz", "Händler und Handwerker", "Kirche: Marienkirche", "Schutz: Wall und Graben", "Bewohner hießen Bürger"],
  m: "Um den Marktplatz entstanden Häuser und kleine Gassen der Händler und Handwerker. Sie bauten die Marienkirche. Zum Schutz schütteten sie einen Wall auf und legten einen Graben an. Die Bewohner nannten sich Bürger." },
{ id: "q5", st: "probe", typ: "erklaer", f: "Die Butenburg (um 1200) und die Neustadt (um 1300): Was entstand dort, welche Kirchen, welcher Schutz?",
  k: ["Butenburg: Handwerker und Bauern siedeln sich an", "Katharinenkirche", "Neue große Mauer und Wassergraben", "Neustadt: Bischof baut Johanniskirche", "1306 gemeinsame Stadtmauer"],
  m: "In der Butenburg siedelten sich Handwerker und Bauern an; ihre Kirche war die Katharinenkirche. Binnen- und Butenburg bauten eine große Mauer und einen Wassergraben. In der Neustadt ließ der Bischof die Johanniskirche und Schulen bauen. 1306 bekamen Alt- und Neustadt eine gemeinsame Mauer." },
{ id: "q6", st: "probe", typ: "erklaer", f: "Der Ablasshandel: Was ist das, wie funktionierte er, und warum gab es ihn?",
  k: ["Kirche verkaufte Ablassbriefe", "Angeblich von Sünden freikaufen", "Menschen hatten Angst vor Strafe nach dem Tod", "Kirche machte Geschäfte mit der Angst"],
  m: "Die Kirche verkaufte Ablassbriefe. Wer einen kaufte, sollte sich damit angeblich von seinen Sünden freikaufen. Die Menschen hatten Angst, nach dem Tod für ihre Sünden büßen zu müssen, und die Kirche machte mit dieser Angst Geschäfte." },
{ id: "q7", st: "probe", typ: "erklaer", f: "Die Reformation: Was ist sie, wann fand sie statt, wer war beteiligt, was war der Auslöser, und was veränderte sich?",
  k: ["Erneuerung der Kirche", "1517, 95 Thesen", "Martin Luther (Mönch) und Protestanten; Gegner Papst und Kaiser", "Auslöser: Missstände, Ablasshandel", "Spaltung in katholisch und evangelisch, Bibel auf Deutsch"],
  m: "Die Reformation ist die Erneuerung der Kirche. Sie begann 1517, als der Mönch Martin Luther 95 Thesen machte. Er ärgerte sich, dass Papst und Bischöfe reich lebten und mit dem Ablasshandel Geschäfte machten. Seine Anhänger hießen Protestanten. Die Kirche spaltete sich in katholisch und evangelisch, und Luther übersetzte die Bibel ins Deutsche." },
{ id: "q8", st: "probe", typ: "erklaer", f: "Der Augsburger Religionsfrieden: Was ist er, wer hat ihn beschlossen, und wann?",
  k: ["Katholiken und Protestanten gleichberechtigt", "Kaiser und protestantische Fürsten", "1555 in Augsburg"],
  m: "Der Augsburger Religionsfrieden ist ein Vertrag, der Katholiken und Protestanten gleichstellte. Der Kaiser und die protestantischen Fürsten schlossen ihn 1555 in Augsburg." },
{ id: "q9", st: "probe", typ: "erklaer", f: "Der Prager Fenstersturz: Was, wann, wo, wer und warum?",
  k: ["1618", "Prag in Böhmen, königliche Burg", "Evangelische Adelige warfen Verwalter des Königs aus dem Fenster", "Grund: katholischer König unterdrückte Protestanten", "Auslöser des Krieges"],
  m: "1618 stürmten evangelische Adelige in Prag (Böhmen) die königliche Burg und warfen die Verwalter des katholischen Königs aus dem Fenster. Der König hatte die Protestanten unterdrückt. Damit begann der Dreißigjährige Krieg." },
{ id: "q10", st: "probe", typ: "erklaer", f: "Der Dreißigjährige Krieg: Wer kämpfte gegen wen, und worum ging es?",
  k: ["Katholiken gegen Protestanten", "Katholisch: Kaiser, katholische Fürsten, Spanien", "Protestantisch: Fürsten, Dänemark, Schweden, Frankreich half", "Glaube und Macht in Europa"],
  m: "Katholiken kämpften gegen Protestanten, zuerst in Deutschland, dann ganz Europa: der Kaiser, die katholischen Fürsten und Spanien gegen die protestantischen Fürsten, Dänemark und Schweden, unterstützt von Frankreich. Es ging um den richtigen Glauben und um Macht." },
{ id: "q11", st: "probe", typ: "erklaer", f: "Der Westfälische Frieden: Was ist er, was wurde beschlossen, wann und wo, und wer war beteiligt?",
  k: ["Beendete den Dreißigjährigen Krieg durch Verhandlungen", "Gleiche Rechte für alle christlichen Konfessionen u. a.", "24.10.1648 unterzeichnet in Münster, 25.10. verkündet in Osnabrück", "Verhandelt in Osnabrück und Münster", "Gesandte aus ganz Europa"],
  m: "Der Westfälische Frieden beendete 1648 den Dreißigjährigen Krieg, zum ersten Mal durch Verhandlungen. Beschlossen wurde unter anderem, dass alle christlichen Konfessionen gleiche Rechte haben. Gesandte aus ganz Europa verhandelten fünf Jahre in Osnabrück und Münster; am 24. Oktober 1648 wurde in Münster unterzeichnet, am 25. Oktober verkündete der Bürgermeister den Frieden in Osnabrück." },
{ id: "q12", st: "probe", typ: "erklaer", f: "Das Steckenpferdreiten: Was ist es, woher kommt die Tradition, und warum wird es gefeiert?",
  k: ["Umzug aller 4. Klassen mit Steckenpferden, Rathaustreppe, Brezel", "Nürnberg 1650: Kinder ritten zum Fürsten Piccolomini", "1875 nach Osnabrück verlegt (Dincklage), erstes Reiten 1948", "Erinnerung an die Verkündung des Friedens 1648"],
  m: "Beim Steckenpferdreiten ziehen alle 4. Klassen mit selbstgebastelten Steckenpferden durch die Stadt und reiten über die Rathaustreppe. Die Tradition kommt aus Nürnberg: 1650 ritten dort Kinder zum Fürsten Piccolomini. Die Dichterinnen von Dincklage verlegten die Geschichte 1875 nach Osnabrück. Gefeiert wird zur Erinnerung an die Verkündung des Westfälischen Friedens am 25. Oktober 1648." }
]
};
